# Generated by Django 5.2.15 on 2026-10-06 19:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curve', '0024_manual_draft_reconstruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualGate2ControlV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True, editable=False)),
                ('product_id', models.UUIDField(editable=False)),
                ('initiative_id', models.UUIDField(editable=False)),
                ('version', models.PositiveBigIntegerField(editable=False)),
                ('current_record_id', models.UUIDField(editable=False)),
                ('subject_id', models.UUIDField(editable=False)),
                ('state', models.CharField(editable=False, max_length=24)),
                ('approved_record_id', models.UUIDField(editable=False, null=True)),
            ],
            options={
                'db_table': 'curve_manual_gate2_control_v2',
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'id'), name='curve_mg2c_ws_id_uq'), models.UniqueConstraint(fields=('workspace_id', 'initiative_id'), name='curve_mg2c_init_uq'), models.CheckConstraint(condition=models.Q(('version__gte', 1), ('version__lte', 9007199254740991)), name='curve_mg2c_ver_ck'), models.CheckConstraint(condition=models.Q(('state__in', ['PLAN_REVIEW', 'CHANGES_REQUESTED', 'MANUAL_APPROVED', 'RELEASED'])), name='curve_mg2c_state_ck')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ManualGate2RecordV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True, editable=False)),
                ('product_id', models.UUIDField(editable=False)),
                ('initiative_id', models.UUIDField(db_index=True, editable=False)),
                ('control_id', models.UUIDField(editable=False)),
                ('version', models.PositiveBigIntegerField(editable=False)),
                ('initiative_version', models.PositiveBigIntegerField(editable=False)),
                ('predecessor_id', models.UUIDField(editable=False, null=True)),
                ('action', models.CharField(editable=False, max_length=24)),
                ('subject_id', models.UUIDField(editable=False)),
                ('subject_digest', models.CharField(editable=False, max_length=71)),
                ('draft_revision_id', models.UUIDField(editable=False)),
                ('digest', models.CharField(editable=False, max_length=71)),
                ('payload', models.JSONField(editable=False)),
                ('request_payload', models.JSONField(editable=False)),
                ('request_digest', models.CharField(editable=False, max_length=71)),
                ('policy_decision_id', models.UUIDField(editable=False)),
                ('command_receipt_id', models.UUIDField(editable=False)),
                ('created_by', models.UUIDField(editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'curve_manual_gate2_record_v2',
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'id'), name='curve_mg2r_ws_id_uq'), models.UniqueConstraint(fields=('workspace_id', 'control_id', 'version'), name='curve_mg2r_seq_uq'), models.UniqueConstraint(fields=('workspace_id', 'command_receipt_id'), name='curve_mg2r_event_uq'), models.UniqueConstraint(fields=('workspace_id', 'policy_decision_id'), name='curve_mg2r_policy_uq'), models.CheckConstraint(condition=models.Q(('version__gte', 1), ('version__lte', 9007199254740991)), name='curve_mg2r_ver_ck'), models.CheckConstraint(condition=models.Q(('initiative_version__gte', 2), ('initiative_version__lte', 9007199254740991)), name='curve_mg2r_init_ver_ck'), models.CheckConstraint(condition=models.Q(('action__in', ['PREPARE', 'APPROVE', 'REQUEST_CHANGES', 'RECONCILE', 'RELEASE'])), name='curve_mg2r_action_ck'), models.CheckConstraint(condition=models.Q(('digest__regex', '^sha256:[0-9a-f]{64}$')), name='curve_mg2r_digest_ck'), models.CheckConstraint(condition=models.Q(('subject_digest__regex', '^sha256:[0-9a-f]{64}$')), name='curve_mg2r_subject_ck'), models.CheckConstraint(condition=models.Q(('request_digest__regex', '^sha256:[0-9a-f]{64}$')), name='curve_mg2r_request_ck')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ManualTaskClaimV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True, editable=False)),
                ('installation_id', models.UUIDField(editable=False)),
                ('issue_id', models.UUIDField(editable=False)),
                ('initiative_id', models.UUIDField(db_index=True, editable=False)),
                ('subject_id', models.UUIDField(editable=False)),
                ('generation', models.PositiveBigIntegerField(editable=False)),
                ('state', models.CharField(editable=False, max_length=16)),
                ('current_record_id', models.UUIDField(editable=False)),
                ('current_history_id', models.UUIDField(editable=False)),
            ],
            options={
                'db_table': 'curve_manual_task_claim_v2',
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'id'), name='curve_mtc2_ws_id_uq'), models.UniqueConstraint(fields=('workspace_id', 'installation_id', 'issue_id'), name='curve_mtc2_task_uq'), models.CheckConstraint(condition=models.Q(('generation__gte', 1), ('generation__lte', 9007199254740991)), name='curve_mtc2_gen_ck'), models.CheckConstraint(condition=models.Q(('state__in', ['ACTIVE', 'RELEASED'])), name='curve_mtc2_state_ck')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='ManualTaskClaimHistoryV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True, editable=False)),
                ('claim_id', models.UUIDField(editable=False)),
                ('record_id', models.UUIDField(editable=False)),
                ('initiative_id', models.UUIDField(db_index=True, editable=False)),
                ('generation', models.PositiveBigIntegerField(editable=False)),
                ('state', models.CharField(editable=False, max_length=16)),
                ('payload', models.JSONField(editable=False)),
            ],
            options={
                'db_table': 'curve_manual_task_claim_history_v2',
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'id'), name='curve_mtch2_ws_id_uq'), models.UniqueConstraint(fields=('workspace_id', 'claim_id', 'record_id'), name='curve_mtch2_event_uq'), models.CheckConstraint(condition=models.Q(('generation__gte', 1), ('generation__lte', 9007199254740991)), name='curve_mtch2_gen_ck'), models.CheckConstraint(condition=models.Q(('state__in', ['ACTIVE', 'RELEASED'])), name='curve_mtch2_state_ck')],
                'indexes': [],
            },
        ),
    ]
