# Generated by Django for the additive Curve application boundary.

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = []
