# Generated by Django 5.2.15 on 2026-08-17 19:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("curve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.CharField(default="1.0", editable=False, max_length=20)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("sequence", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=128)),
                ("target_type", models.CharField(editable=False, max_length=100)),
                ("target_id", models.UUIDField(editable=False)),
                ("target_ref", models.JSONField(editable=False)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ALLOWED", "Allowed"),
                            ("DENIED", "Denied"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("NO_EFFECT", "No effect"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor", models.JSONField(editable=False)),
                ("effective_principal", models.JSONField(blank=True, editable=False, null=True)),
                ("policy_decision_ref", models.JSONField(blank=True, editable=False, null=True)),
                ("before_digest", models.CharField(blank=True, editable=False, max_length=71, null=True)),
                ("after_digest", models.CharField(blank=True, editable=False, max_length=71, null=True)),
                ("details_ref", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("correlation_id", models.CharField(editable=False, max_length=255)),
                ("causation_id", models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ("idempotency_key_digest", models.CharField(blank=True, editable=False, max_length=71, null=True)),
            ],
            options={
                "db_table": "curve_audit_event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace_id", "target_type", "target_id", "sequence"),
                        name="curve_audit_workspace_target_seq_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)), name="curve_audit_sequence_positive_ck"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.CharField(default="1.0", editable=False, max_length=20)),
                ("event_type", models.CharField(max_length=255)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.UUIDField()),
                ("aggregate_version", models.PositiveBigIntegerField()),
                ("sequence", models.PositiveBigIntegerField()),
                ("initiative_id", models.UUIDField(blank=True, null=True)),
                ("workflow_version_id", models.UUIDField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.JSONField(editable=False)),
                ("effective_principal", models.JSONField(blank=True, editable=False, null=True)),
                ("correlation_id", models.CharField(editable=False, max_length=255)),
                ("causation_id", models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ("idempotency_key_digest", models.CharField(blank=True, editable=False, max_length=71, null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("payload_schema", models.CharField(max_length=1000)),
                ("payload", models.JSONField()),
            ],
            options={
                "db_table": "curve_domain_event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace_id", "aggregate_type", "aggregate_id", "sequence"),
                        name="curve_event_workspace_aggregate_seq_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)), name="curve_event_sequence_positive_ck"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("aggregate_version__gte", 1)), name="curve_event_version_positive_ck"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.CharField(default="1.0", editable=False, max_length=20)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("principal_scope", models.CharField(max_length=500)),
                ("command_scope", models.CharField(max_length=500)),
                ("key_digest", models.CharField(editable=False, max_length=71)),
                ("request_digest", models.CharField(editable=False, max_length=71)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED_TERMINAL", "Failed terminal"),
                            ("RECONCILIATION_REQUIRED", "Reconciliation required"),
                        ],
                        default="IN_PROGRESS",
                        max_length=32,
                    ),
                ),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_digest", models.CharField(blank=True, max_length=71, null=True)),
                ("response_resource_ref", models.JSONField(blank=True, null=True)),
                ("external_effect_refs", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "curve_idempotency_record",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace_id", "principal_scope", "command_scope", "key_digest"),
                        name="curve_idem_workspace_principal_cmd_key_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state__in", ["COMPLETED", "FAILED_TERMINAL"]), _negated=True),
                            models.Q(
                                ("response_status__isnull", False),
                                ("response_digest__isnull", False),
                                ("response_resource_ref__isnull", False),
                                ("completed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="curve_idem_terminal_fields_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("response_status__isnull", True),
                            models.Q(("response_status__gte", 100), ("response_status__lte", 599)),
                            _connector="OR",
                        ),
                        name="curve_idem_response_status_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InboxMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.CharField(default="1.0", editable=False, max_length=20)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("consumer_id", models.CharField(max_length=255)),
                ("event_id", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED_TERMINAL", "Failed terminal"),
                        ],
                        default="RECEIVED",
                        max_length=32,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("result_digest", models.CharField(blank=True, max_length=71, null=True)),
                ("last_error", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "curve_inbox_message",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace_id", "consumer_id", "event_id"),
                        name="curve_inbox_workspace_consumer_event_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "PROCESSED"), _negated=True),
                            models.Q(("processed_at__isnull", False), ("result_digest__isnull", False)),
                            _connector="OR",
                        ),
                        name="curve_inbox_processed_fields_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "FAILED_TERMINAL"), _negated=True),
                            models.Q(("processed_at__isnull", False), ("last_error__isnull", False)),
                            _connector="OR",
                        ),
                        name="curve_inbox_failed_fields_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("aggregate_version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.JSONField(editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.JSONField(editable=False)),
                ("tombstoned_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("tombstoned_by", models.JSONField(blank=True, editable=False, null=True)),
                ("tombstone_reason", models.TextField(blank=True, editable=False, null=True)),
                ("schema_version", models.CharField(default="1.0", editable=False, max_length=20)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("FOUNDATION_PROBE", "Foundation probe"),
                            ("WORKFLOW_COMMAND", "Workflow command"),
                            ("PROVIDER_RECONCILIATION", "Provider reconciliation"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("WAITING_FOR_HUMAN", "Waiting for human"),
                            ("CANCEL_REQUESTED", "Cancel requested"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("command_type", models.CharField(max_length=100)),
                ("target", models.JSONField()),
                ("idempotency_key_digest", models.CharField(max_length=71)),
                ("causation_id", models.CharField(blank=True, max_length=255, null=True)),
                ("workflow_id", models.CharField(blank=True, max_length=1000, null=True)),
                ("policy_version_ref", models.JSONField(blank=True, null=True)),
                ("progress_percent", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("progress_summary", models.CharField(blank=True, max_length=2000, null=True)),
                ("result_ref", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("effective_principal", models.JSONField(blank=True, null=True)),
                ("correlation_id", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "curve_operation",
                "indexes": [models.Index(fields=["workspace_id", "status"], name="curve_op_workspace_state_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status__in", ["SUCCEEDED", "FAILED", "CANCELLED"]), _negated=True),
                            ("completed_at__isnull", False),
                            _connector="OR",
                        ),
                        name="curve_op_terminal_completed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "FAILED"), _negated=True), ("error__isnull", False), _connector="OR"
                        ),
                        name="curve_op_failed_error_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("progress_percent__isnull", True), ("progress_percent__lte", 100), _connector="OR"
                        ),
                        name="curve_op_progress_range_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("aggregate_version__gte", 1)), name="curve_op_version_positive_ck"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.CharField(default="1.0", editable=False, max_length=20)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("event_id", models.UUIDField(editable=False)),
                ("destination", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CLAIMED", "Claimed"),
                            ("DELIVERED", "Delivered"),
                            ("RETRY_SCHEDULED", "Retry scheduled"),
                            ("DEAD_LETTER", "Dead letter"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=255, null=True)),
                ("claimed_until", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "curve_outbox_event",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "state", "next_attempt_at", "created_at"], name="curve_outbox_due_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace_id", "event_id", "destination"), name="curve_outbox_workspace_event_dest_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "CLAIMED"), _negated=True),
                            models.Q(
                                ("claimed_by__isnull", False),
                                models.Q(("claimed_by", ""), _negated=True),
                                ("claimed_until__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="curve_outbox_claim_fields_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "RETRY_SCHEDULED"), _negated=True),
                            models.Q(("next_attempt_at__isnull", False), ("last_error__isnull", False)),
                            _connector="OR",
                        ),
                        name="curve_outbox_retry_fields_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "DELIVERED"), _negated=True),
                            ("delivered_at__isnull", False),
                            _connector="OR",
                        ),
                        name="curve_outbox_delivered_at_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "DEAD_LETTER"), _negated=True),
                            ("last_error__isnull", False),
                            _connector="OR",
                        ),
                        name="curve_outbox_dead_error_ck",
                    ),
                ],
            },
        ),
    ]
