# Generated by Django 5.2.15 on 2026-08-18

import uuid

from django.db import migrations, models
import django.db.models.lookups


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(default="1.0", editable=False, max_length=20),
                ),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("sequence", models.PositiveBigIntegerField(editable=False)),
                ("action", models.CharField(editable=False, max_length=128)),
                ("resource_type", models.CharField(editable=False, max_length=100)),
                ("resource_id", models.UUIDField(editable=False)),
                (
                    "resource_version",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                    ),
                ),
                ("subject", models.JSONField(editable=False)),
                ("effective_principal", models.JSONField(editable=False)),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow"),
                            ("DENY", "Deny"),
                            (
                                "REQUIRE_HUMAN_CONFIRMATION",
                                "Require human confirmation",
                            ),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("reason_codes", models.JSONField(editable=False)),
                (
                    "policy_key",
                    models.CharField(
                        default="CURVE_CORE_POLICY",
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "policy_version",
                    models.PositiveIntegerField(default=1, editable=False),
                ),
                (
                    "policy_manifest_digest",
                    models.CharField(editable=False, max_length=71),
                ),
                ("input_digest", models.CharField(editable=False, max_length=71)),
                (
                    "normalized_classification",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "permitted_projection",
                    models.JSONField(default=list, editable=False),
                ),
                ("correlation_id", models.CharField(editable=False, max_length=255)),
                ("evaluated_at", models.DateTimeField(editable=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.JSONField(editable=False)),
            ],
            options={
                "db_table": "curve_policy_decision",
                "indexes": [
                    models.Index(
                        fields=["workspace_id", "-evaluated_at"],
                        name="curve_policy_ws_eval_idx",
                    ),
                    models.Index(
                        fields=[
                            "workspace_id",
                            "resource_type",
                            "resource_id",
                            "-evaluated_at",
                        ],
                        name="curve_policy_res_eval_idx",
                    ),
                    models.Index(
                        fields=["workspace_id", "effect", "-evaluated_at"],
                        name="curve_policy_effect_eval_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "workspace_id",
                            "resource_type",
                            "resource_id",
                            "sequence",
                        ),
                        name="curve_policy_ws_res_seq_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="curve_policy_seq_pos_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resource_version__isnull", True),
                            ("resource_version__gte", 1),
                            _connector="OR",
                        ),
                        name="curve_policy_res_ver_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("effect", "ALLOW"),
                                models.Q(("permitted_projection", []), _negated=True),
                            ),
                            models.Q(
                                models.Q(("effect", "ALLOW"), _negated=True),
                                ("permitted_projection", []),
                            ),
                            _connector="OR",
                        ),
                        name="curve_policy_proj_effect_ck",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.lookups.Exact(
                            models.Func(
                                models.F("permitted_projection"),
                                function="jsonb_typeof",
                            ),
                            models.Value("array"),
                        ),
                        name="curve_policy_proj_type_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.Exact(
                                models.Func(
                                    models.F("reason_codes"),
                                    function="jsonb_typeof",
                                ),
                                models.Value("array"),
                            ),
                            django.db.models.lookups.GreaterThan(
                                models.Func(
                                    models.F("reason_codes"),
                                    function="jsonb_array_length",
                                    output_field=models.IntegerField(),
                                ),
                                models.Value(0),
                            ),
                        ),
                        name="curve_policy_reasons_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "policy_manifest_digest__regex",
                                "^sha256:[0-9a-f]{64}$",
                            )
                        ),
                        name="curve_policy_manifest_sha_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("input_digest__regex", "^sha256:[0-9a-f]{64}$")
                        ),
                        name="curve_policy_input_sha_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", "1.0")),
                        name="curve_policy_schema_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("policy_key", "CURVE_CORE_POLICY"),
                            ("policy_version", 1),
                        ),
                        name="curve_policy_identity_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recorded_by__actor_type__in", ["SERVICE", "SYSTEM"])
                        ),
                        name="curve_policy_recorder_type_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recorded_at__gte", models.F("evaluated_at"))
                        ),
                        name="curve_policy_recorded_time_ck",
                    ),
                ],
            },
        ),
    ]
