# Generated by Django 5.2.15 on 2026-08-22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0003_policydecision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policydecision",
            name="recorded_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
            ),
        ),
    ]
