# Generated by Django 5.2.15 on 2026-08-28 12:45

import django.db.models.deletion
import django.db.models.lookups
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0004_policydecision_recorded_at_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCapability",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("schema_version", models.CharField(default="2.0", editable=False, max_length=20)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("connection_version", models.PositiveBigIntegerField(editable=False)),
                ("capability_version", models.PositiveBigIntegerField(editable=False)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("FAKE_LOCAL", "Fake local"),
                            ("ONYX", "Onyx"),
                            ("MCP", "MCP"),
                            ("ORCA_HUMAN_ASSISTANCE", "Orca human assistance"),
                            ("MODEL_GATEWAY", "Model gateway"),
                            ("OPENHANDS", "OpenHands"),
                            ("GITHUB", "GitHub"),
                            ("GITLAB", "GitLab"),
                            ("QUALITY", "Quality"),
                            ("FEATURE_FLAG", "Feature flag"),
                            ("DOCUMENTATION", "Documentation"),
                            ("MONITORING", "Monitoring"),
                            ("PROTOTYPE", "Prototype"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("adapter_key", models.CharField(editable=False, max_length=100)),
                ("adapter_version", models.CharField(editable=False, max_length=100)),
                ("protocol_versions", models.JSONField(editable=False)),
                ("capabilities", models.JSONField(editable=False)),
                ("allowed_classifications", models.JSONField(editable=False)),
                ("observed_at", models.DateTimeField(editable=False)),
                ("validated_at", models.DateTimeField(editable=False)),
                ("expires_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "curve_provider_capability",
            },
        ),
        migrations.CreateModel(
            name="ProviderConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("aggregate_version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.JSONField(editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.JSONField(editable=False)),
                ("tombstoned_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("tombstoned_by", models.JSONField(blank=True, editable=False, null=True)),
                ("tombstone_reason", models.TextField(blank=True, editable=False, null=True)),
                ("schema_version", models.CharField(default="2.0", editable=False, max_length=20)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("FAKE_LOCAL", "Fake local"),
                            ("ONYX", "Onyx"),
                            ("MCP", "MCP"),
                            ("ORCA_HUMAN_ASSISTANCE", "Orca human assistance"),
                            ("MODEL_GATEWAY", "Model gateway"),
                            ("OPENHANDS", "OpenHands"),
                            ("GITHUB", "GitHub"),
                            ("GITLAB", "GitLab"),
                            ("QUALITY", "Quality"),
                            ("FEATURE_FLAG", "Feature flag"),
                            ("DOCUMENTATION", "Documentation"),
                            ("MONITORING", "Monitoring"),
                            ("PROTOTYPE", "Prototype"),
                        ],
                        max_length=32,
                    ),
                ),
                ("adapter_key", models.CharField(max_length=100)),
                ("adapter_version", models.CharField(max_length=100)),
                (
                    "environment",
                    models.CharField(
                        choices=[("LOCAL", "Local"), ("STAGING", "Staging"), ("PRODUCTION", "Production")],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("external_tenant_ref", models.CharField(blank=True, max_length=1000, null=True)),
                ("configuration_ref", models.JSONField(blank=True, null=True)),
                ("configuration_digest", models.CharField(max_length=71)),
                ("secret_reference", models.CharField(blank=True, max_length=1000, null=True)),
                ("allowed_classifications", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VALIDATION", "Pending validation"),
                            ("ACTIVE", "Active"),
                            ("DEGRADED", "Degraded"),
                            ("DISABLED", "Disabled"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING_VALIDATION",
                        max_length=32,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validation_result_ref", models.JSONField(blank=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("next_reconcile_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "curve_provider_connection",
            },
        ),
        migrations.RemoveConstraint(
            model_name="policydecision",
            name="curve_policy_identity_ck",
        ),
        migrations.AddConstraint(
            model_name="policydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_key", "CURVE_CORE_POLICY"), ("policy_version__in", [1, 2])),
                name="curve_policy_identity_ck",
            ),
        ),
        migrations.AddField(
            model_name="providerconnection",
            name="current_capability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for_connections",
                to="curve.providercapability",
            ),
        ),
        migrations.AddField(
            model_name="providercapability",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capability_history",
                to="curve.providerconnection",
            ),
        ),
        migrations.AddIndex(
            model_name="providerconnection",
            index=models.Index(fields=["workspace_id", "status", "next_reconcile_at"], name="curve_pconn_ws_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "environment", "adapter_key"), name="curve_pconn_ws_env_adapter_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("aggregate_version__gte", 1)), name="curve_pconn_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "2.0")), name="curve_pconn_schema_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("configuration_digest__regex", "^sha256:[0-9a-f]{64}$")),
                name="curve_pconn_digest_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["PENDING_VALIDATION", "ACTIVE", "DEGRADED", "DISABLED", "REVOKED"])),
                name="curve_pconn_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    models.Func(models.F("allowed_classifications"), function="jsonb_typeof"), models.Value("array")
                ),
                name="curve_pconn_class_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_type", "FAKE_LOCAL"),
                    ("adapter_key", "curve.fake-local"),
                    ("environment", "LOCAL"),
                    ("external_tenant_ref__isnull", True),
                    ("configuration_ref__isnull", True),
                    ("secret_reference__isnull", True),
                    ("allowed_classifications", ["INTERNAL"]),
                ),
                name="curve_pconn_fake_local_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["ACTIVE", "DEGRADED"]), _negated=True),
                    models.Q(
                        ("current_capability__isnull", False),
                        ("last_reconciled_at__isnull", False),
                        ("validated_at__isnull", False),
                        ("validation_result_ref__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="curve_pconn_live_refs_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ACTIVE"), _negated=True), ("next_reconcile_at__isnull", False), _connector="OR"
                ),
                name="curve_pconn_active_next_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "DEGRADED"), _negated=True), ("last_error__isnull", False), _connector="OR"
                ),
                name="curve_pconn_degraded_err_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["DISABLED", "REVOKED"]), _negated=True),
                    ("next_reconcile_at__isnull", True),
                    _connector="OR",
                ),
                name="curve_pconn_stopped_next_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("validation_result_ref__isnull", True),
                    django.db.models.lookups.Exact(
                        models.Func(models.F("validation_result_ref"), function="jsonb_typeof"), models.Value("object")
                    ),
                    _connector="OR",
                ),
                name="curve_pconn_result_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_error__isnull", True),
                    django.db.models.lookups.Exact(
                        models.Func(models.F("last_error"), function="jsonb_typeof"), models.Value("object")
                    ),
                    _connector="OR",
                ),
                name="curve_pconn_error_type_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="providercapability",
            index=models.Index(fields=["workspace_id", "-validated_at"], name="curve_pcap_ws_valid_idx"),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "connection", "capability_version"), name="curve_pcap_ws_conn_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=models.Q(("connection_version__gte", 1)), name="curve_pcap_conn_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=models.Q(("capability_version__gte", 1)), name="curve_pcap_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", "2.0")), name="curve_pcap_schema_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("provider_type", "FAKE_LOCAL"),
                    ("adapter_key", "curve.fake-local"),
                    ("protocol_versions", ["curve.fake-local/v1"]),
                    ("allowed_classifications", ["INTERNAL"]),
                ),
                name="curve_pcap_fake_local_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    django.db.models.lookups.Exact(
                        models.Func(models.F("protocol_versions"), function="jsonb_typeof"), models.Value("array")
                    ),
                    django.db.models.lookups.GreaterThan(
                        models.Func(
                            models.F("protocol_versions"),
                            function="jsonb_array_length",
                            output_field=models.IntegerField(),
                        ),
                        models.Value(0),
                    ),
                ),
                name="curve_pcap_protocols_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    django.db.models.lookups.Exact(
                        models.Func(models.F("capabilities"), function="jsonb_typeof"), models.Value("array")
                    ),
                    django.db.models.lookups.GreaterThan(
                        models.Func(
                            models.F("capabilities"), function="jsonb_array_length", output_field=models.IntegerField()
                        ),
                        models.Value(0),
                    ),
                ),
                name="curve_pcap_capabilities_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="providercapability",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    models.Func(models.F("allowed_classifications"), function="jsonb_typeof"), models.Value("array")
                ),
                name="curve_pcap_class_type_ck",
            ),
        ),
    ]
