# Generated by Django 5.2.15 on 2026-09-05 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


GUARDS = """
ALTER TABLE curve_prd_accepted_command ADD CONSTRAINT curve_prd_cmd_operation_fk
 FOREIGN KEY (workspace_id, operation_id) REFERENCES curve_operation(workspace_id, id);
ALTER TABLE curve_prd_accepted_command ADD CONSTRAINT curve_prd_cmd_init_fk
 FOREIGN KEY (workspace_id, initiative_id) REFERENCES curve_initiative(workspace_id, id);
CREATE TRIGGER curve_prd_cmd_immutable BEFORE UPDATE OR DELETE ON curve_prd_accepted_command
 FOR EACH ROW EXECUTE FUNCTION curve_prd_immutable();
CREATE FUNCTION curve_prd_command_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE init curve_initiative%ROWTYPE; op curve_operation%ROWTYPE;
 cp curve_document_checkpoint%ROWTYPE; gate curve_gate_assignment%ROWTYPE;
 keys text[]; id_key text;
BEGIN
 SELECT * INTO init FROM curve_initiative WHERE workspace_id=NEW.workspace_id AND id=NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR init.version <> NEW.expected_version THEN
  RAISE EXCEPTION 'PRD_COMMAND_VERSION_CONFLICT' USING ERRCODE='23514';
 END IF;
 SELECT * INTO op FROM curve_operation WHERE workspace_id=NEW.workspace_id AND id=NEW.operation_id FOR UPDATE;
 IF NOT FOUND OR op.operation_type <> 'WORKFLOW_COMMAND' OR op.status <> 'PENDING'
  OR op.command_type <> replace(NEW.action, 'CURVE.PRD.', 'PRD_')
  OR op.target IS DISTINCT FROM jsonb_build_object('resource_type','INITIATIVE',
   'resource_id',NEW.initiative_id::text,'resource_version',NEW.expected_version)
  OR op.created_by IS DISTINCT FROM jsonb_build_object('actor_type','HUMAN','actor_id',NEW.actor_id::text)
  OR (op.effective_principal IS NOT NULL AND op.effective_principal IS DISTINCT FROM op.created_by)
  OR NOT isfinite(NEW.accepted_at) OR NEW.accepted_at < op.created_at THEN
  RAISE EXCEPTION 'PRD_COMMAND_OPERATION_MISMATCH' USING ERRCODE='23514';
 END IF;
 PERFORM 1 FROM curve_policy_decision WHERE workspace_id=NEW.workspace_id
  AND id::text=op.policy_version_ref->>'resource_id' AND op.policy_version_ref->>'resource_type'='POLICY_DECISION'
  AND action=NEW.action AND effect='ALLOW' AND policy_key='CURVE_PRD_POLICY'
  AND resource_type='INITIATIVE' AND resource_id=NEW.initiative_id AND resource_version=NEW.expected_version
  AND subject=op.created_by AND effective_principal=op.created_by;
 IF NOT FOUND THEN RAISE EXCEPTION 'PRD_COMMAND_POLICY_MISMATCH' USING ERRCODE='23514'; END IF;
 IF NEW.action = 'CURVE.PRD.SUBMIT' THEN
  keys := ARRAY['external_document_binding_id','evidence_snapshot_id','completeness_check_id'];
  IF init.state NOT IN ('ALIGNING','PRD_REVIEW') THEN
   RAISE EXCEPTION 'PRD_COMMAND_STATE_CONFLICT' USING ERRCODE='23514';
  END IF;
  IF num_nonnulls(NEW.rationale_object_id,NEW.rationale_digest,NEW.rationale_size_bytes,
   NEW.rationale_access_envelope_id,NEW.rationale_retention_policy_version_id) <> 0 THEN
   RAISE EXCEPTION 'PRD_COMMAND_RATIONALE_INVALID' USING ERRCODE='23514';
  END IF;
 ELSE
  keys := ARRAY['gate_assignment_id','checkpoint_id','artifact_version_id','content_digest',
   'provider_version','evidence_snapshot_id','confirmed_risk_tier'];
  IF NEW.action IN ('CURVE.PRD.REQUEST_CHANGES','CURVE.PRD.REJECT') THEN keys := keys || ARRAY['decision']; END IF;
  IF init.state <> 'PRD_REVIEW' THEN
   RAISE EXCEPTION 'PRD_COMMAND_STATE_CONFLICT' USING ERRCODE='23514';
  END IF;
  IF num_nonnulls(NEW.rationale_object_id,NEW.rationale_digest,NEW.rationale_size_bytes,
   NEW.rationale_access_envelope_id,NEW.rationale_retention_policy_version_id) <> 5
   OR NEW.rationale_digest !~ '^sha256:[0-9a-f]{64}$' OR NEW.rationale_size_bytes NOT BETWEEN 1 AND 8000 THEN
   RAISE EXCEPTION 'PRD_COMMAND_RATIONALE_INVALID' USING ERRCODE='23514';
  END IF;
 END IF;
 IF jsonb_typeof(NEW.subject) IS DISTINCT FROM 'object' THEN
  RAISE EXCEPTION 'PRD_COMMAND_SUBJECT_INVALID' USING ERRCODE='23514';
 END IF;
 IF NOT NEW.subject ?& keys OR NEW.subject - keys <> '{}'::jsonb
  OR EXISTS(SELECT 1 FROM jsonb_each(NEW.subject) v WHERE jsonb_typeof(v.value) <> 'string') THEN
  RAISE EXCEPTION 'PRD_COMMAND_SUBJECT_INVALID' USING ERRCODE='23514';
 END IF;
 FOREACH id_key IN ARRAY keys LOOP
  IF id_key LIKE '%_id'
   AND (NEW.subject->>id_key) !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
   RAISE EXCEPTION 'PRD_COMMAND_SUBJECT_INVALID' USING ERRCODE='23514';
  END IF;
 END LOOP;
 IF NEW.action = 'CURVE.PRD.SUBMIT' THEN
  PERFORM 1 FROM curve_external_document_binding WHERE workspace_id=NEW.workspace_id
   AND initiative_id=NEW.initiative_id AND id=(NEW.subject->>'external_document_binding_id')::uuid;
  IF NOT FOUND THEN RAISE EXCEPTION 'PRD_COMMAND_BINDING_MISMATCH' USING ERRCODE='23514'; END IF;
 ELSE
  SELECT * INTO cp FROM curve_document_checkpoint WHERE workspace_id=NEW.workspace_id
   AND initiative_id=NEW.initiative_id AND id=(NEW.subject->>'checkpoint_id')::uuid;
  IF NOT FOUND OR cp.id IS DISTINCT FROM init.current_prd_checkpoint_id
   OR cp.artifact_version_id::text <> NEW.subject->>'artifact_version_id'
   OR cp.evidence_snapshot_id::text <> NEW.subject->>'evidence_snapshot_id'
   OR cp.content_digest <> NEW.subject->>'content_digest'
   OR cp.provider_version <> NEW.subject->>'provider_version'
   OR init.risk_tier <> NEW.subject->>'confirmed_risk_tier' THEN
   RAISE EXCEPTION 'PRD_COMMAND_CHECKPOINT_MISMATCH' USING ERRCODE='23514';
  END IF;
  SELECT * INTO gate FROM curve_gate_assignment WHERE workspace_id=NEW.workspace_id
   AND initiative_id=NEW.initiative_id AND id=(NEW.subject->>'gate_assignment_id')::uuid;
  IF NOT FOUND OR gate.gate_type <> 'PRD_APPROVAL' OR gate.approver_user_id <> NEW.actor_id THEN
   RAISE EXCEPTION 'PRD_COMMAND_ASSIGNMENT_MISMATCH' USING ERRCODE='23514';
  END IF;
  IF (NEW.action='CURVE.PRD.REQUEST_CHANGES' AND NEW.subject->>'decision' <> 'CHANGES_REQUESTED')
   OR (NEW.action='CURVE.PRD.REJECT' AND NEW.subject->>'decision' <> 'REJECTED') THEN
   RAISE EXCEPTION 'PRD_COMMAND_DECISION_MISMATCH' USING ERRCODE='23514';
  END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER curve_prd_command_guard BEFORE INSERT ON curve_prd_accepted_command
 FOR EACH ROW EXECUTE FUNCTION curve_prd_command_guard();
"""

REVERSE_GUARDS = """
LOCK TABLE curve_prd_accepted_command IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM curve_prd_accepted_command) THEN
  RAISE EXCEPTION 'Retained PRD commands require a preservation migration';
 END IF;
END $$;
DROP TRIGGER curve_prd_command_guard ON curve_prd_accepted_command;
DROP FUNCTION curve_prd_command_guard();
DROP TRIGGER curve_prd_cmd_immutable ON curve_prd_accepted_command;
ALTER TABLE curve_prd_accepted_command DROP CONSTRAINT curve_prd_cmd_init_fk;
ALTER TABLE curve_prd_accepted_command DROP CONSTRAINT curve_prd_cmd_operation_fk;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0014_prd_policy_identity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(fields=["workspace_id", "id"], name="curve_operation_scope_uq"),
        ),
        migrations.CreateModel(
            name="PrdAcceptedCommand",
            fields=[
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="curve.operation",
                    ),
                ),
                ("workspace_id", models.UUIDField(editable=False)),
                ("actor_id", models.UUIDField(editable=False)),
                ("action", models.CharField(editable=False, max_length=32)),
                ("expected_version", models.PositiveBigIntegerField(editable=False)),
                ("request_digest", models.CharField(editable=False, max_length=71)),
                ("subject", models.JSONField(editable=False)),
                ("accepted_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("rationale_object_id", models.UUIDField(editable=False, null=True)),
                ("rationale_digest", models.CharField(editable=False, max_length=71, null=True)),
                ("rationale_size_bytes", models.PositiveIntegerField(editable=False, null=True)),
                ("rationale_access_envelope_id", models.UUIDField(editable=False, null=True)),
                ("rationale_retention_policy_version_id", models.UUIDField(editable=False, null=True)),
                ("initiative", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="curve.initiative")),
            ],
            options={
                "db_table": "curve_prd_accepted_command",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                [
                                    "CURVE.PRD.SUBMIT",
                                    "CURVE.PRD.APPROVE",
                                    "CURVE.PRD.REQUEST_CHANGES",
                                    "CURVE.PRD.REJECT",
                                ],
                            )
                        ),
                        name="curve_prd_cmd_action_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expected_version__gte", 1), ("expected_version__lte", 9007199254740991)),
                        name="curve_prd_cmd_version_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("request_digest__regex", "^sha256:[0-9a-f]{64}$")),
                        name="curve_prd_cmd_digest_ck",
                    ),
                ],
            },
        ),
        migrations.RunSQL(GUARDS, REVERSE_GUARDS),
    ]
