# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15 on 2026-10-03 21:51

import django.utils.timezone
import uuid
from django.db import migrations, models


FORWARD_GUARDS = """
ALTER TABLE curve_project_association
    ADD CONSTRAINT curve_passoc_product_tenant_fk
    FOREIGN KEY (workspace_id, product_id)
    REFERENCES curve_product (workspace_id, id) ON DELETE RESTRICT;
CREATE FUNCTION curve_guard_project_association() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Association history cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.version <> 1 OR NEW.state <> 'ACTIVE' THEN
            RAISE EXCEPTION 'Association must start ACTIVE at version one' USING ERRCODE = '23514';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM projects WHERE id = NEW.source_project_id
                       AND workspace_id = NEW.workspace_id AND deleted_at IS NULL AND archived_at IS NULL)
           OR NOT EXISTS (SELECT 1 FROM curve_product WHERE id = NEW.product_id
                          AND workspace_id = NEW.workspace_id AND state = 'ACTIVE') THEN
            RAISE EXCEPTION 'Association source and Product must exist in its workspace and be active'
                USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;
    IF ROW(NEW.id, NEW.workspace_id, NEW.provider_installation_id, NEW.source_project_id, NEW.product_id,
           NEW.effective_at, NEW.initiated_by, NEW.policy_edition, NEW.command_receipt_id,
           NEW.source_observed_at, NEW.source_version)
       IS DISTINCT FROM
       ROW(OLD.id, OLD.workspace_id, OLD.provider_installation_id, OLD.source_project_id, OLD.product_id,
           OLD.effective_at, OLD.initiated_by, OLD.policy_edition, OLD.command_receipt_id,
           OLD.source_observed_at, OLD.source_version) THEN
        RAISE EXCEPTION 'Association identity and initial observation are immutable' USING ERRCODE = '23514';
    END IF;
    IF OLD.state <> 'ACTIVE' OR NEW.state <> 'ENDED' OR NEW.version <> OLD.version + 1 THEN
        RAISE EXCEPTION 'Only ACTIVE to ENDED at the next version is permitted' USING ERRCODE = '23514';
    END IF;
    IF length(btrim(NEW.end_reason)) = 0 THEN
        RAISE EXCEPTION 'Ending requires a reason' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER curve_project_association_guard
    BEFORE INSERT OR UPDATE OR DELETE ON curve_project_association
    FOR EACH ROW EXECUTE FUNCTION curve_guard_project_association();
"""

REVERSE_GUARDS = """
LOCK TABLE curve_project_association, curve_policy_decision, curve_audit_event,
           curve_domain_event, curve_outbox_event IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM curve_project_association)
       OR EXISTS (SELECT 1 FROM curve_policy_decision WHERE policy_key = 'CURVE_PROJECT_ASSOCIATION_POLICY')
       OR EXISTS (SELECT 1 FROM curve_audit_event WHERE action LIKE 'CURVE.PROJECT_ASSOCIATION.%')
       OR EXISTS (SELECT 1 FROM curve_domain_event WHERE aggregate_type = 'PROJECT_ASSOCIATION')
       OR EXISTS (SELECT 1 FROM curve_outbox_event WHERE destination = 'CURVE_PROJECT_ASSOCIATION_LOCAL_V1') THEN
        RAISE EXCEPTION 'Retained association evidence requires a preservation migration' USING ERRCODE = '23514';
    END IF;
END $$;
DROP TRIGGER curve_project_association_guard ON curve_project_association;
DROP FUNCTION curve_guard_project_association();
ALTER TABLE curve_project_association DROP CONSTRAINT curve_passoc_product_tenant_fk;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0019_prd_evidence_git_retention"),
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAssociation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("provider_installation_id", models.UUIDField(editable=False)),
                ("source_project_id", models.UUIDField(editable=False)),
                ("product_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ENDED", "Ended")], default="ACTIVE", max_length=16
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("effective_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("initiated_by", models.UUIDField(editable=False)),
                (
                    "policy_edition",
                    models.CharField(default="EXPLICIT_EXISTING_PROJECT_ASSOCIATION_V1", editable=False, max_length=64),
                ),
                ("command_receipt_id", models.UUIDField(editable=False)),
                ("source_observed_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("source_version", models.CharField(editable=False, max_length=64)),
                ("ended_at", models.DateTimeField(editable=False, null=True)),
                ("ended_by", models.UUIDField(editable=False, null=True)),
                ("end_reason", models.CharField(editable=False, max_length=1000, null=True)),
                ("end_receipt_id", models.UUIDField(editable=False, null=True)),
            ],
            options={
                "db_table": "curve_project_association",
            },
        ),
        migrations.RemoveConstraint(
            model_name="policydecision",
            name="curve_policy_identity_ck",
        ),
        migrations.AddConstraint(
            model_name="policydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("policy_key", "CURVE_PROJECT_ASSOCIATION_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:0ea402f3db6a7fb0743a79a45644d79235a685781ad844d3c42230da2c548691",
                        ),
                        ("policy_version", 1),
                    ),
                    models.Q(("policy_key", "CURVE_CORE_POLICY"), ("policy_version__in", [1, 2])),
                    models.Q(("policy_key", "CURVE_PRODUCT_POLICY"), ("policy_version", 1)),
                    models.Q(("policy_key", "CURVE_INITIATIVE_POLICY"), ("policy_version", 1)),
                    models.Q(
                        ("policy_key", "CURVE_PRD_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:ad38408f0e4450c615025debdf3361965f3a7361ad392aaf9aeb4219b910cb4c",
                        ),
                        ("policy_version", 1),
                    ),
                    _connector="OR",
                ),
                name="curve_policy_identity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("workspace_id", "id"), name="curve_product_ws_id_uq"),
        ),
        migrations.AddIndex(
            model_name="projectassociation",
            index=models.Index(fields=["workspace_id", "product_id", "state"], name="curve_passoc_product_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "ACTIVE")),
                fields=("workspace_id", "provider_installation_id", "source_project_id"),
                name="curve_passoc_active_source_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectassociation",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="curve_passoc_version_ck"),
        ),
        migrations.AddConstraint(
            model_name="projectassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_edition", "EXPLICIT_EXISTING_PROJECT_ASSOCIATION_V1")),
                name="curve_passoc_policy_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_version", ""), _negated=True), name="curve_passoc_source_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("end_reason__isnull", True),
                        ("end_receipt_id__isnull", True),
                        ("ended_at__isnull", True),
                        ("ended_by__isnull", True),
                        ("state", "ACTIVE"),
                    ),
                    models.Q(
                        ("end_reason__isnull", False),
                        ("end_receipt_id__isnull", False),
                        ("ended_at__isnull", False),
                        ("ended_by__isnull", False),
                        ("state", "ENDED"),
                        models.Q(("end_reason", ""), _negated=True),
                        ("ended_at__gte", models.F("effective_at")),
                    ),
                    _connector="OR",
                ),
                name="curve_passoc_end_fields_ck",
            ),
        ),
        migrations.RunSQL(FORWARD_GUARDS, REVERSE_GUARDS),
    ]
