# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Generated by Django 5.2.15 on 2026-10-03 22:33

import django.utils.timezone
import uuid
from django.db import migrations, models


FORWARD_GUARDS = """
ALTER TABLE curve_scope_proposal ADD CONSTRAINT curve_scope_initiative_fk
 FOREIGN KEY (workspace_id, initiative_id) REFERENCES curve_initiative (workspace_id, id) ON DELETE RESTRICT;
ALTER TABLE curve_scope_proposal ADD CONSTRAINT curve_scope_product_fk
 FOREIGN KEY (workspace_id, product_id) REFERENCES curve_product (workspace_id, id) ON DELETE RESTRICT;
ALTER TABLE curve_scope_proposal_revision ADD CONSTRAINT curve_scope_revision_head_fk
 FOREIGN KEY (workspace_id, proposal_id) REFERENCES curve_scope_proposal (workspace_id, id)
 DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE curve_scope_proposal ADD CONSTRAINT curve_scope_current_revision_fk
 FOREIGN KEY (workspace_id, current_revision_id) REFERENCES curve_scope_proposal_revision (workspace_id, id)
 DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE curve_scope_proposal_revision ADD CONSTRAINT curve_scope_predecessor_fk
 FOREIGN KEY (workspace_id, predecessor_id) REFERENCES curve_scope_proposal_revision (workspace_id, id);
ALTER TABLE curve_scope_proposal_item ADD CONSTRAINT curve_scope_item_revision_fk
 FOREIGN KEY (workspace_id, revision_id) REFERENCES curve_scope_proposal_revision (workspace_id, id);

CREATE FUNCTION curve_guard_scope_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE initiative curve_initiative; head curve_scope_proposal;
BEGIN
 IF TG_OP <> 'INSERT' THEN
  RAISE EXCEPTION 'Scope revision history is immutable' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO initiative FROM curve_initiative
  WHERE workspace_id = NEW.workspace_id AND id = NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR initiative.product_id <> NEW.product_id OR initiative.mode <> 'STANDALONE'
   OR initiative.state <> 'DRAFT' OR NEW.initiative_version <> initiative.version + 1
   OR NOT EXISTS (SELECT 1 FROM curve_product WHERE workspace_id = NEW.workspace_id
                  AND id = NEW.product_id AND state = 'ACTIVE')
   OR NOT EXISTS (SELECT 1 FROM users WHERE id = NEW.created_by AND is_active AND NOT is_bot)
   OR NOT EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = NEW.workspace_id
                  AND member_id = NEW.created_by AND is_active AND deleted_at IS NULL
                  AND role IN (5, 15, 20) AND (role = 20 OR initiative.creator_user_id = NEW.created_by)) THEN
  RAISE EXCEPTION 'Scope revision requires current Draft authority' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO head FROM curve_scope_proposal
  WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.initiative_id FOR UPDATE;
 IF FOUND THEN
  IF NEW.proposal_id <> head.id OR NEW.version <> head.version + 1
     OR NEW.predecessor_id IS DISTINCT FROM head.current_revision_id THEN
   RAISE EXCEPTION 'Scope revision predecessor/version mismatch' USING ERRCODE = '23514';
  END IF;
 ELSIF NEW.version <> 1 OR NEW.predecessor_id IS NOT NULL THEN
  RAISE EXCEPTION 'Scope revision must start at one' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER curve_scope_revision_guard BEFORE INSERT OR UPDATE OR DELETE ON curve_scope_proposal_revision
 FOR EACH ROW EXECUTE FUNCTION curve_guard_scope_revision();

CREATE FUNCTION curve_guard_scope_item() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE revision curve_scope_proposal_revision; association curve_project_association;
BEGIN
 IF TG_OP <> 'INSERT' THEN
  RAISE EXCEPTION 'Scope member history is immutable' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO revision FROM curve_scope_proposal_revision
  WHERE workspace_id = NEW.workspace_id AND id = NEW.revision_id;
 IF NOT FOUND OR EXISTS (SELECT 1 FROM curve_scope_proposal WHERE workspace_id = NEW.workspace_id
                         AND id = revision.proposal_id AND version >= revision.version)
    OR (SELECT count(*) FROM curve_scope_proposal_item WHERE workspace_id = NEW.workspace_id
        AND revision_id = NEW.revision_id) >= revision.item_count THEN
  RAISE EXCEPTION 'Scope revision members are sealed or out of bounds' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO association FROM curve_project_association
  WHERE workspace_id = NEW.workspace_id AND id = NEW.association_id FOR UPDATE;
 IF NOT FOUND OR association.version <> NEW.association_version OR association.state <> 'ACTIVE'
    OR association.product_id <> revision.product_id
    OR association.provider_installation_id <> NEW.provider_installation_id
    OR association.source_project_id <> NEW.source_project_id THEN
  RAISE EXCEPTION 'Scope association identity/version invalid' USING ERRCODE = '23514';
 END IF;
 IF NOT EXISTS (
  SELECT 1 FROM issues i JOIN projects p ON p.id = i.project_id
   JOIN states s ON s.id = i.state_id
   JOIN project_members m ON m.project_id = p.id AND m.member_id = revision.created_by
  WHERE i.id = NEW.source_issue_id AND i.workspace_id = NEW.workspace_id AND i.project_id = NEW.source_project_id
   AND i.deleted_at IS NULL AND i.archived_at IS NULL AND NOT i.is_draft
   AND p.workspace_id = NEW.workspace_id AND p.deleted_at IS NULL AND p.archived_at IS NULL
   AND s.workspace_id = NEW.workspace_id AND s.project_id = p.id AND s.deleted_at IS NULL AND s."group" <> 'triage'
   AND m.workspace_id = NEW.workspace_id AND m.deleted_at IS NULL AND m.is_active AND m.role IN (5, 15, 20)
   AND (m.role <> 5 OR p.guest_view_all_features OR i.created_by_id = revision.created_by)
 ) THEN
  RAISE EXCEPTION 'Scope member requires current native visibility' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER curve_scope_item_guard BEFORE INSERT OR UPDATE OR DELETE ON curve_scope_proposal_item
 FOR EACH ROW EXECUTE FUNCTION curve_guard_scope_item();

CREATE FUNCTION curve_guard_scope_head() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE revision curve_scope_proposal_revision; initiative curve_initiative;
BEGIN
 IF TG_OP = 'DELETE' THEN
  RAISE EXCEPTION 'Scope history cannot be deleted' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO initiative FROM curve_initiative
  WHERE workspace_id = NEW.workspace_id AND id = NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR initiative.product_id <> NEW.product_id OR initiative.mode <> 'STANDALONE'
    OR initiative.state <> 'DRAFT' THEN
  RAISE EXCEPTION 'Scope head requires same-Product Draft Initiative' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO revision FROM curve_scope_proposal_revision
  WHERE workspace_id = NEW.workspace_id AND id = NEW.current_revision_id;
 IF NOT FOUND OR revision.proposal_id <> NEW.id OR revision.initiative_id <> NEW.initiative_id
    OR revision.product_id <> NEW.product_id OR revision.version <> NEW.version
    OR revision.initiative_version <> initiative.version THEN
  RAISE EXCEPTION 'Scope head revision mismatch' USING ERRCODE = '23514';
 END IF;
 IF TG_OP = 'UPDATE' THEN
  IF ROW(NEW.id, NEW.workspace_id, NEW.initiative_id, NEW.product_id)
      IS DISTINCT FROM ROW(OLD.id, OLD.workspace_id, OLD.initiative_id, OLD.product_id)
     OR NEW.version <> OLD.version + 1 OR revision.predecessor_id IS DISTINCT FROM OLD.current_revision_id THEN
   RAISE EXCEPTION 'Scope head cannot rewrite identity or reuse a revision' USING ERRCODE = '23514';
  END IF;
 ELSIF NEW.version <> 1 OR revision.predecessor_id IS NOT NULL THEN
  RAISE EXCEPTION 'Scope head must start at revision one' USING ERRCODE = '23514';
 END IF;
 IF revision.item_count <> (SELECT count(*) FROM curve_scope_proposal_item
                            WHERE workspace_id = NEW.workspace_id AND revision_id = revision.id)
   OR revision.delivery_count <> (SELECT count(*) FROM curve_scope_proposal_item
                                  WHERE workspace_id = NEW.workspace_id AND revision_id = revision.id
                                   AND purpose = 'PROPOSED_DELIVERY') THEN
  RAISE EXCEPTION 'Scope head cannot publish partial members' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER curve_scope_head_guard BEFORE INSERT OR UPDATE OR DELETE ON curve_scope_proposal
 FOR EACH ROW EXECUTE FUNCTION curve_guard_scope_head();

CREATE FUNCTION curve_verify_scope_commit() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM curve_scope_proposal WHERE workspace_id = NEW.workspace_id
                AND id = NEW.proposal_id AND initiative_id = NEW.initiative_id
                AND product_id = NEW.product_id AND version >= NEW.version)
   OR NEW.item_count <> (SELECT count(*) FROM curve_scope_proposal_item
                         WHERE workspace_id = NEW.workspace_id AND revision_id = NEW.id)
   OR NEW.delivery_count <> (SELECT count(*) FROM curve_scope_proposal_item
                             WHERE workspace_id = NEW.workspace_id AND revision_id = NEW.id
                              AND purpose = 'PROPOSED_DELIVERY')
   OR NOT EXISTS (SELECT 1 FROM curve_domain_event WHERE workspace_id = NEW.workspace_id
                  AND id = NEW.command_receipt_id AND aggregate_type = 'SCOPE_PROPOSAL'
                  AND aggregate_id = NEW.proposal_id AND aggregate_version = NEW.version)
   OR NOT EXISTS (SELECT 1 FROM curve_outbox_event WHERE workspace_id = NEW.workspace_id
                  AND event_id = NEW.command_receipt_id AND destination = 'CURVE_SCOPE_PROPOSAL_LOCAL_V1') THEN
  RAISE EXCEPTION 'Scope revision must commit its head/members/event/outbox atomically' USING ERRCODE = '23514';
 END IF;
 RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER curve_scope_commit_guard AFTER INSERT ON curve_scope_proposal_revision
 DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION curve_verify_scope_commit();

CREATE FUNCTION curve_scope_prd_transition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF (NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id
     OR (NEW.controlling_prd_decision_id IS DISTINCT FROM OLD.controlling_prd_decision_id
         AND EXISTS (SELECT 1 FROM curve_prd_review_decision WHERE id = NEW.controlling_prd_decision_id
                     AND state = 'APPROVED')))
    AND EXISTS (SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
                ON i.workspace_id = h.workspace_id AND i.revision_id = h.current_revision_id
                WHERE h.workspace_id = NEW.workspace_id AND h.initiative_id = NEW.id
                 AND i.purpose = 'PROPOSED_DELIVERY') THEN
  RAISE EXCEPTION 'PRD_SCOPE_BRIDGE_UNAVAILABLE' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER curve_scope_prd_transition_guard BEFORE UPDATE ON curve_initiative
 FOR EACH ROW EXECUTE FUNCTION curve_scope_prd_transition_guard();
"""

REVERSE_GUARDS = """
LOCK TABLE curve_scope_proposal, curve_scope_proposal_revision, curve_scope_proposal_item,
 curve_policy_decision, curve_audit_event, curve_domain_event, curve_outbox_event, curve_idempotency_record
 IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM curve_scope_proposal) OR EXISTS (SELECT 1 FROM curve_scope_proposal_revision)
  OR EXISTS (SELECT 1 FROM curve_scope_proposal_item)
  OR EXISTS (SELECT 1 FROM curve_policy_decision WHERE policy_key = 'CURVE_SCOPE_PROPOSAL_POLICY')
  OR EXISTS (SELECT 1 FROM curve_audit_event WHERE action LIKE 'CURVE.SCOPE_PROPOSAL.%')
  OR EXISTS (SELECT 1 FROM curve_domain_event WHERE aggregate_type = 'SCOPE_PROPOSAL')
  OR EXISTS (SELECT 1 FROM curve_outbox_event WHERE destination = 'CURVE_SCOPE_PROPOSAL_LOCAL_V1')
  OR EXISTS (SELECT 1 FROM curve_idempotency_record WHERE command_scope LIKE 'CURVE.SCOPE_PROPOSAL.%') THEN
  RAISE EXCEPTION 'Retained scope evidence requires a preservation migration' USING ERRCODE = '23514';
 END IF;
END $$;
DROP TRIGGER curve_scope_prd_transition_guard ON curve_initiative;
DROP FUNCTION curve_scope_prd_transition_guard();
DROP TRIGGER curve_scope_commit_guard ON curve_scope_proposal_revision;
DROP FUNCTION curve_verify_scope_commit();
DROP TRIGGER curve_scope_head_guard ON curve_scope_proposal;
DROP FUNCTION curve_guard_scope_head();
DROP TRIGGER curve_scope_item_guard ON curve_scope_proposal_item;
DROP FUNCTION curve_guard_scope_item();
DROP TRIGGER curve_scope_revision_guard ON curve_scope_proposal_revision;
DROP FUNCTION curve_guard_scope_revision();
ALTER TABLE curve_scope_proposal_item DROP CONSTRAINT curve_scope_item_revision_fk;
ALTER TABLE curve_scope_proposal_revision DROP CONSTRAINT curve_scope_predecessor_fk;
ALTER TABLE curve_scope_proposal DROP CONSTRAINT curve_scope_current_revision_fk;
ALTER TABLE curve_scope_proposal_revision DROP CONSTRAINT curve_scope_revision_head_fk;
ALTER TABLE curve_scope_proposal DROP CONSTRAINT curve_scope_product_fk;
ALTER TABLE curve_scope_proposal DROP CONSTRAINT curve_scope_initiative_fk;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0020_project_association"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeProposal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("initiative_id", models.UUIDField(editable=False)),
                ("product_id", models.UUIDField(editable=False)),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("current_revision_id", models.UUIDField(editable=False)),
            ],
            options={
                "db_table": "curve_scope_proposal",
            },
        ),
        migrations.CreateModel(
            name="ScopeProposalItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("revision_id", models.UUIDField(editable=False)),
                ("association_id", models.UUIDField(editable=False)),
                ("association_version", models.PositiveBigIntegerField(editable=False)),
                ("provider_installation_id", models.UUIDField(editable=False)),
                ("source_project_id", models.UUIDField(editable=False)),
                ("source_issue_id", models.UUIDField(editable=False)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("CONTEXT_EVIDENCE", "Context evidence"), ("PROPOSED_DELIVERY", "Proposed delivery")],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("source_observed_at", models.DateTimeField(editable=False)),
                ("source_version", models.CharField(editable=False, max_length=64)),
                ("source_fingerprint", models.CharField(editable=False, max_length=71)),
            ],
            options={
                "db_table": "curve_scope_proposal_item",
            },
        ),
        migrations.CreateModel(
            name="ScopeProposalRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("proposal_id", models.UUIDField(editable=False)),
                ("initiative_id", models.UUIDField(editable=False)),
                ("product_id", models.UUIDField(editable=False)),
                ("version", models.PositiveBigIntegerField(editable=False)),
                ("initiative_version", models.PositiveBigIntegerField(editable=False)),
                ("predecessor_id", models.UUIDField(editable=False, null=True)),
                ("item_count", models.PositiveSmallIntegerField(editable=False)),
                ("delivery_count", models.PositiveSmallIntegerField(editable=False)),
                ("membership_digest", models.CharField(editable=False, max_length=71)),
                ("created_by", models.UUIDField(editable=False)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                (
                    "policy_edition",
                    models.CharField(default="EXPLICIT_EXISTING_WORK_SCOPE_PROPOSAL_V1", editable=False, max_length=64),
                ),
                ("command_receipt_id", models.UUIDField(editable=False)),
            ],
            options={
                "db_table": "curve_scope_proposal_revision",
            },
        ),
        migrations.RemoveConstraint(
            model_name="policydecision",
            name="curve_policy_identity_ck",
        ),
        migrations.AddConstraint(
            model_name="policydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("policy_key", "CURVE_PROJECT_ASSOCIATION_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:0ea402f3db6a7fb0743a79a45644d79235a685781ad844d3c42230da2c548691",
                        ),
                        ("policy_version", 1),
                    ),
                    models.Q(
                        ("policy_key", "CURVE_SCOPE_PROPOSAL_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:778bdbd6fb82f51482d791d22ae6cf884a8906e91613b07cdafc6b429d24e266",
                        ),
                        ("policy_version", 1),
                    ),
                    models.Q(("policy_key", "CURVE_CORE_POLICY"), ("policy_version__in", [1, 2])),
                    models.Q(("policy_key", "CURVE_PRODUCT_POLICY"), ("policy_version", 1)),
                    models.Q(("policy_key", "CURVE_INITIATIVE_POLICY"), ("policy_version", 1)),
                    models.Q(
                        ("policy_key", "CURVE_PRD_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:ad38408f0e4450c615025debdf3361965f3a7361ad392aaf9aeb4219b910cb4c",
                        ),
                        ("policy_version", 1),
                    ),
                    _connector="OR",
                ),
                name="curve_policy_identity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposal",
            constraint=models.UniqueConstraint(fields=("workspace_id", "id"), name="curve_scope_ws_id_uq"),
        ),
        migrations.AddConstraint(
            model_name="scopeproposal",
            constraint=models.UniqueConstraint(fields=("workspace_id", "initiative_id"), name="curve_scope_init_uq"),
        ),
        migrations.AddConstraint(
            model_name="scopeproposal",
            constraint=models.CheckConstraint(condition=models.Q(("version__gte", 1)), name="curve_scope_version_ck"),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalitem",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "revision_id", "source_issue_id"), name="curve_scope_item_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("association_version__gte", 1)), name="curve_scope_assoc_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["CONTEXT_EVIDENCE", "PROPOSED_DELIVERY"])),
                name="curve_scope_purpose_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_version", ""), _negated=True), name="curve_scope_source_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_fingerprint__regex", "^sha256:[0-9a-f]{64}$")),
                name="curve_scope_source_digest_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.UniqueConstraint(fields=("workspace_id", "id"), name="curve_scope_rev_ws_id_uq"),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "proposal_id", "version"), name="curve_scope_rev_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="curve_scope_rev_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("initiative_version__gte", 2)), name="curve_scope_init_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_count__lte", 100)), name="curve_scope_item_count_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("delivery_count__lte", models.F("item_count"))),
                name="curve_scope_delivery_count_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("membership_digest__regex", "^sha256:[0-9a-f]{64}$")), name="curve_scope_digest_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_edition", "EXPLICIT_EXISTING_WORK_SCOPE_PROPOSAL_V1")),
                name="curve_scope_policy_ck",
            ),
        ),
        migrations.RunSQL(FORWARD_GUARDS, REVERSE_GUARDS),
    ]
