# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Additive exact scope reopening with immutable provenance and physical coverage."""

# Generated by Django 5.2.15 on 2026-10-04 21:30

import django.utils.timezone
import uuid
from django.db import migrations, models

# Frozen SQL is intentionally independent of runtime contract/model loaders.
# ruff: noqa: E501

BASELINE_CATALOG_DIGEST = "sha256:274da118f1814386702114f8ac6dcc39f29a7726a2f184a9cc56c44f00c1d046"
SUCCESSOR_CATALOG_DIGEST = "sha256:e44c580ea214e03b315c2b14c038cb14ae5d99fa8a60115e82d6b5841ac177a7"

CATALOG_SQL = r"""SELECT jsonb_build_object(
 'tables', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,name),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS name,c.relkind AS kind,c.relpersistence AS persistence,
   c.relrowsecurity AS row_security,c.relforcerowsecurity AS force_row_security
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND c.relkind IN ('r','p','v','m','f')
   AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'columns', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,position),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,row_number() OVER (PARTITION BY n.nspname,c.relname ORDER BY a.attnum) AS position,a.attname AS name,
   format_type(a.atttypid,a.atttypmod) AS data_type,a.attnotnull AS not_null,a.attidentity AS identity_kind,
   a.attgenerated AS generated_kind,pg_get_expr(d.adbin,d.adrelid,true) AS default_expression,
   co.collname AS collation
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid
  LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum LEFT JOIN pg_collation co ON co.oid=a.attcollation
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND c.relkind IN ('r','p','v','m','f')
   AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND a.attnum>0 AND NOT a.attisdropped) r),
 'constraints', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,name),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,k.conname AS name,k.contype AS kind,
   pg_get_constraintdef(k.oid,true) AS definition,k.condeferrable AS deferrable,
   k.condeferred AS initially_deferred,k.convalidated AS validated,k.connoinherit AS no_inherit
  FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'triggers', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,name,definition),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,
   CASE WHEN t.tgisinternal THEN '<internal>' ELSE t.tgname END AS name,t.tgisinternal AS internal,
   t.tgenabled AS enabled,CASE WHEN t.tgisinternal THEN regexp_replace(pg_get_triggerdef(t.oid,true),
    'TRIGGER "?RI_ConstraintTrigger_[ac]_[0-9]+"?', 'TRIGGER <internal>') ELSE pg_get_triggerdef(t.oid,true) END AS definition,
   k.conname AS constraint_name,pn.nspname AS function_schema,p.proname AS function_name,
   pg_get_function_identity_arguments(p.oid) AS function_identity_arguments
  FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
  JOIN pg_proc p ON p.oid=t.tgfoid JOIN pg_namespace pn ON pn.oid=p.pronamespace
  LEFT JOIN pg_constraint k ON k.oid=t.tgconstraint
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'indexes', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,name),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,i.relname AS name,pg_get_indexdef(i.oid) AS definition,
   x.indisunique AS unique,x.indisprimary AS primary_key,x.indisvalid AS valid,x.indisready AS ready
  FROM pg_index x JOIN pg_class c ON c.oid=x.indrelid JOIN pg_class i ON i.oid=x.indexrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'functions', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,name,identity_arguments),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,p.proname AS name,pg_get_function_identity_arguments(p.oid) AS identity_arguments,
   pg_get_functiondef(p.oid) AS definition,p.proconfig AS configuration
  FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
  WHERE p.prokind IN ('f','p') AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema'
   AND (p.proname LIKE 'curve\_%' ESCAPE '\' OR EXISTS(
    SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
     WHERE t.tgfoid=p.oid AND c.relname LIKE 'curve\_%' ESCAPE '\'))) r)
)
"""

FORWARD_GUARDS = r"""
CREATE TABLE curve_scope_reopening_coverage (
 edition text PRIMARY KEY,
 catalog_digest text NOT NULL CHECK(catalog_digest ~ '^sha256:[0-9a-f]{64}$')
);
CREATE FUNCTION curve_scope_reopening_catalog() RETURNS jsonb LANGUAGE sql STABLE
 SET search_path=pg_catalog,public AS $catalog$
SELECT jsonb_build_object(
 'tables', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,name),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS name,c.relkind AS kind,c.relpersistence AS persistence,
   c.relrowsecurity AS row_security,c.relforcerowsecurity AS force_row_security
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND c.relkind IN ('r','p','v','m','f')
   AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'columns', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,position),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,row_number() OVER (PARTITION BY n.nspname,c.relname ORDER BY a.attnum) AS position,a.attname AS name,
   format_type(a.atttypid,a.atttypmod) AS data_type,a.attnotnull AS not_null,a.attidentity AS identity_kind,
   a.attgenerated AS generated_kind,pg_get_expr(d.adbin,d.adrelid,true) AS default_expression,
   co.collname AS collation
  FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid
  LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum LEFT JOIN pg_collation co ON co.oid=a.attcollation
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND c.relkind IN ('r','p','v','m','f')
   AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema' AND a.attnum>0 AND NOT a.attisdropped) r),
 'constraints', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,name),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,k.conname AS name,k.contype AS kind,
   pg_get_constraintdef(k.oid,true) AS definition,k.condeferrable AS deferrable,
   k.condeferred AS initially_deferred,k.convalidated AS validated,k.connoinherit AS no_inherit
  FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'triggers', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,name,definition),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,
   CASE WHEN t.tgisinternal THEN '<internal>' ELSE t.tgname END AS name,t.tgisinternal AS internal,
   t.tgenabled AS enabled,CASE WHEN t.tgisinternal THEN regexp_replace(pg_get_triggerdef(t.oid,true),
    'TRIGGER "?RI_ConstraintTrigger_[ac]_[0-9]+"?', 'TRIGGER <internal>') ELSE pg_get_triggerdef(t.oid,true) END AS definition,
   k.conname AS constraint_name,pn.nspname AS function_schema,p.proname AS function_name,
   pg_get_function_identity_arguments(p.oid) AS function_identity_arguments
  FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
  JOIN pg_proc p ON p.oid=t.tgfoid JOIN pg_namespace pn ON pn.oid=p.pronamespace
  LEFT JOIN pg_constraint k ON k.oid=t.tgconstraint
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'indexes', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,table_name,name),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,c.relname AS table_name,i.relname AS name,pg_get_indexdef(i.oid) AS definition,
   x.indisunique AS unique,x.indisprimary AS primary_key,x.indisvalid AS valid,x.indisready AS ready
  FROM pg_index x JOIN pg_class c ON c.oid=x.indrelid JOIN pg_class i ON i.oid=x.indexrelid
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE c.relname LIKE 'curve\_%' ESCAPE '\' AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema') r),
 'functions', (SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY schema,name,identity_arguments),'[]'::jsonb) FROM (
  SELECT n.nspname AS schema,p.proname AS name,pg_get_function_identity_arguments(p.oid) AS identity_arguments,
   pg_get_functiondef(p.oid) AS definition,p.proconfig AS configuration
  FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
  WHERE p.prokind IN ('f','p') AND n.nspname NOT LIKE 'pg_%' AND n.nspname<>'information_schema'
   AND (p.proname LIKE 'curve\_%' ESCAPE '\' OR EXISTS(
    SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
     WHERE t.tgfoid=p.oid AND c.relname LIKE 'curve\_%' ESCAPE '\'))) r)
)
$catalog$;
CREATE FUNCTION curve_scope_reopening_verify_coverage() RETURNS void LANGUAGE plpgsql AS $$
DECLARE expected text; actual text;
BEGIN
 SELECT catalog_digest INTO expected FROM curve_scope_reopening_coverage
  WHERE edition='CURVE_PRE_PLAN_C2B_V1';
 actual:='sha256:'||encode(sha256(convert_to(curve_scope_reopening_catalog()::text,'UTF8')),'hex');
 IF expected IS NULL OR expected IS DISTINCT FROM actual OR (SELECT count(*) FROM curve_scope_reopening_coverage)<>1 THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_PREPLAN_COVERAGE_UNAVAILABLE' USING ERRCODE='23514';
 END IF;
END $$;
CREATE FUNCTION curve_reopen_coverage_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 RAISE EXCEPTION 'SCOPE_REOPENING_COVERAGE_IMMUTABLE' USING ERRCODE='23514';
END $$;
CREATE FUNCTION curve_reopen_schema(kind text) RETURNS jsonb LANGUAGE sql IMMUTABLE STRICT AS $$
 SELECT '{"receipt":{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://curve.example.invalid/candidates/scope-reopening-v1/scope-reopening-receipt-v1.schema.json","type":"object","additionalProperties":false,"required":["schema_version","policy_edition","id","workspace_id","product_id","initiative_id","previous_initiative_version","initiative_version","previous_state","state","revision","reason_digest","historical_checkpoint_status","approval_invalidated","prd_authority","created_by","recorded_at","policy_decision_id","command_receipt_id","digest","controlling"],"properties":{"schema_version":{"const":"curve.scope-reopening/v1-candidate"},"policy_edition":{"const":"EXPLICIT_EXISTING_WORK_SCOPE_REOPENING_V1"},"id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"workspace_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"product_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"initiative_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"previous_initiative_version":{"type":"integer","minimum":1,"maximum":9007199254740991},"initiative_version":{"type":"integer","minimum":1,"maximum":9007199254740991},"previous_state":{"enum":["ALIGNING","PRD_REVIEW","PLANNING"]},"state":{"const":"ALIGNING"},"revision":{"type":"object","additionalProperties":false,"required":["schema_version","id","workspace_id","proposal_id","initiative_id","product_id","version","initiative_version","predecessor_id","item_count","delivery_count","membership_digest","created_by","recorded_at","policy_edition","command_receipt_id","controlling","items"],"properties":{"schema_version":{"const":"2.0"},"id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"workspace_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"proposal_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"initiative_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"product_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"version":{"type":"integer","minimum":1,"maximum":9007199254740991},"initiative_version":{"type":"integer","minimum":2,"maximum":9007199254740991},"predecessor_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"item_count":{"type":"integer","minimum":1,"maximum":100},"delivery_count":{"type":"integer","minimum":0,"maximum":100},"membership_digest":{"type":"string","pattern":"^sha256:[0-9a-f]{64}$"},"created_by":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"recorded_at":{"type":"string","format":"date-time"},"policy_edition":{"const":"REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1"},"command_receipt_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"controlling":{"const":false},"items":{"type":"array","maxItems":100,"items":{"type":"object","additionalProperties":false,"required":["association_id","association_version","source_issue_id","purpose","provider_installation_id","source_project_id","source_observed_at","source_version","source_fingerprint"],"properties":{"association_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"association_version":{"type":"integer","minimum":1,"maximum":9007199254740991},"source_issue_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"purpose":{"enum":["CONTEXT_EVIDENCE","PROPOSED_DELIVERY"]},"provider_installation_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"source_project_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"source_observed_at":{"type":"string","format":"date-time"},"source_version":{"type":"string","minLength":1,"maxLength":64},"source_fingerprint":{"type":"string","pattern":"^sha256:[0-9a-f]{64}$"}}},"uniqueItems":true,"minItems":1}}},"reason_digest":{"type":"string","pattern":"^sha256:[0-9a-f]{64}$"},"historical_checkpoint_status":{"enum":["NONE","RETAINED_STALE"]},"approval_invalidated":{"type":"boolean"},"prd_authority":{"const":"REQUIRES_FRESH_SCOPED_SUBMISSION"},"created_by":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"recorded_at":{"type":"string","format":"date-time"},"policy_decision_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"command_receipt_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"digest":{"type":"string","pattern":"^sha256:[0-9a-f]{64}$"},"controlling":{"const":false}}},"event":{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://curve.example.invalid/candidates/scope-reopening-v1/scope-reopening-event-v1.schema.json","type":"object","additionalProperties":false,"required":["schema_version","policy_edition","event_type","reopening_id","reopening_digest","initiative_id","scope_revision_id","policy_decision_id"],"properties":{"schema_version":{"const":"curve.scope-reopening/v1-candidate"},"policy_edition":{"const":"EXPLICIT_EXISTING_WORK_SCOPE_REOPENING_V1"},"event_type":{"const":"CURVE.SCOPE.REOPENED_AND_REPLACED"},"reopening_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"reopening_digest":{"type":"string","pattern":"^sha256:[0-9a-f]{64}$"},"initiative_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"scope_revision_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"},"policy_decision_id":{"type":"string","format":"uuid","pattern":"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"}}}}'::jsonb -> kind
$$;
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_init_fk FOREIGN KEY (workspace_id,initiative_id) REFERENCES curve_initiative(workspace_id,id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_product_fk FOREIGN KEY (workspace_id,product_id) REFERENCES curve_product(workspace_id,id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_proposal_fk FOREIGN KEY (workspace_id,proposal_id) REFERENCES curve_scope_proposal(workspace_id,id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_revision_fk FOREIGN KEY (workspace_id,scope_revision_id) REFERENCES curve_scope_proposal_revision(workspace_id,id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_predecessor_fk FOREIGN KEY (workspace_id,predecessor_revision_id) REFERENCES curve_scope_proposal_revision(workspace_id,id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_checkpoint_fk FOREIGN KEY (workspace_id,initiative_id,previous_checkpoint_id) REFERENCES curve_document_checkpoint(workspace_id,initiative_id,id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_decision_fk FOREIGN KEY (workspace_id,initiative_id,previous_decision_id) REFERENCES curve_prd_review_decision(workspace_id,initiative_id,id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_previous_fk FOREIGN KEY (workspace_id,initiative_id,previous_pending_reopening_id) REFERENCES curve_scope_reopening(workspace_id,initiative_id,id);
ALTER TABLE curve_initiative ADD CONSTRAINT curve_init_pending_reopen_fk FOREIGN KEY (workspace_id,id,pending_scope_reopening_id) REFERENCES curve_scope_reopening(workspace_id,initiative_id,id);
-- Policy/event IDs are scoped in both immediate and deferred guards; existing
-- tables have no workspace/id unique key, so use their primary keys plus checks.
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_policy_fk FOREIGN KEY (policy_decision_id) REFERENCES curve_policy_decision(id);
ALTER TABLE curve_scope_reopening ADD CONSTRAINT curve_reopen_event_fk FOREIGN KEY (command_receipt_id) REFERENCES curve_domain_event(id) DEFERRABLE INITIALLY DEFERRED;

CREATE FUNCTION curve_reopen_fence(r curve_scope_reopening) RETURNS void LANGUAGE plpgsql AS $$
DECLARE init curve_initiative; reviewers uuid[]; actor uuid; member jsonb; src record; source_digest text;
BEGIN
 PERFORM curve_scope_reopening_verify_coverage();
 PERFORM 1 FROM workspaces WHERE id=r.workspace_id FOR UPDATE;
 SELECT * INTO init FROM curve_initiative WHERE workspace_id=r.workspace_id AND id=r.initiative_id FOR UPDATE;
 IF NOT FOUND OR init.product_id<>r.product_id OR init.mode<>'STANDALONE' OR init.schema_version<>'1.1'
  OR init.state NOT IN ('ALIGNING','PRD_REVIEW','PLANNING') OR init.workflow_version_id IS NULL
  OR init.roadmap_item_id IS NOT NULL OR init.first_external_resource_at IS NOT NULL THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_PREPLAN_REQUIRED' USING ERRCODE='23514';
 END IF;
 PERFORM 1 FROM curve_gate_assignment WHERE workspace_id=r.workspace_id AND initiative_id=r.initiative_id ORDER BY id FOR UPDATE;
 PERFORM 1 FROM curve_product WHERE workspace_id=r.workspace_id AND id=r.product_id AND state='ACTIVE' FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'SCOPE_REOPENING_PRODUCT_UNAVAILABLE' USING ERRCODE='23514'; END IF;
 PERFORM 1 FROM users WHERE id IN (SELECT approver_user_id FROM curve_gate_assignment
  WHERE workspace_id=r.workspace_id AND initiative_id=r.initiative_id UNION SELECT r.created_by) ORDER BY id FOR UPDATE;
 PERFORM 1 FROM workspace_members WHERE workspace_id=r.workspace_id AND member_id IN
  (SELECT approver_user_id FROM curve_gate_assignment WHERE workspace_id=r.workspace_id AND initiative_id=r.initiative_id
   UNION SELECT r.created_by) ORDER BY member_id FOR UPDATE;
 SELECT array_agg(g.approver_user_id ORDER BY g.gate_type) INTO reviewers
 FROM curve_gate_assignment g JOIN users u ON u.id=g.approver_user_id
  JOIN workspace_members w ON w.workspace_id=g.workspace_id AND w.member_id=g.approver_user_id
 WHERE g.workspace_id=r.workspace_id AND g.initiative_id=r.initiative_id
  AND g.valid_from<=clock_timestamp() AND (g.valid_until IS NULL OR g.valid_until>clock_timestamp())
  AND u.is_active AND NOT u.is_bot AND w.is_active AND w.deleted_at IS NULL AND w.role IN (5,15,20);
 IF cardinality(reviewers) IS DISTINCT FROM 3
  OR (init.risk_tier IN ('STANDARD','HIGH') AND (SELECT count(DISTINCT id) FROM unnest(reviewers) id)<>3)
  OR NOT EXISTS(SELECT 1 FROM curve_gate_assignment WHERE workspace_id=r.workspace_id
    AND initiative_id=r.initiative_id AND gate_type='PRD_APPROVAL' AND approver_user_id=r.created_by
    AND valid_from<=clock_timestamp() AND (valid_until IS NULL OR valid_until>clock_timestamp())) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_PRODUCT_APPROVER_REQUIRED' USING ERRCODE='23514';
 END IF;
 PERFORM 1 FROM curve_project_association WHERE id IN
  (SELECT (m->>'association_id')::uuid FROM jsonb_array_elements(r.payload->'revision'->'items') m) ORDER BY id FOR UPDATE;
 PERFORM 1 FROM projects WHERE id IN
  (SELECT (m->>'source_project_id')::uuid FROM jsonb_array_elements(r.payload->'revision'->'items') m) ORDER BY id FOR UPDATE;
 PERFORM 1 FROM project_members WHERE project_id IN
  (SELECT (m->>'source_project_id')::uuid FROM jsonb_array_elements(r.payload->'revision'->'items') m) ORDER BY project_id,member_id FOR UPDATE;
 PERFORM 1 FROM issues WHERE id IN
  (SELECT (m->>'source_issue_id')::uuid FROM jsonb_array_elements(r.payload->'revision'->'items') m) ORDER BY id FOR UPDATE;
 PERFORM 1 FROM states WHERE id IN (SELECT state_id FROM issues WHERE id IN
  (SELECT (m->>'source_issue_id')::uuid FROM jsonb_array_elements(r.payload->'revision'->'items') m)) ORDER BY id FOR UPDATE;
 FOR member IN SELECT value FROM jsonb_array_elements(r.payload->'revision'->'items') LOOP
  SELECT i.id,i.workspace_id,i.project_id,i.parent_id,i.state_id,i.created_by_id,i.updated_at,
   s."group" AS state_group,s.updated_at AS state_updated_at INTO src
  FROM issues i JOIN projects p ON p.id=i.project_id JOIN states s ON s.id=i.state_id
   JOIN curve_project_association a ON a.id=(member->>'association_id')::uuid
  WHERE i.id=(member->>'source_issue_id')::uuid AND i.workspace_id=r.workspace_id
   AND i.project_id=(member->>'source_project_id')::uuid AND i.deleted_at IS NULL AND i.archived_at IS NULL AND NOT i.is_draft
   AND p.workspace_id=r.workspace_id AND p.deleted_at IS NULL AND p.archived_at IS NULL
   AND s.workspace_id=r.workspace_id AND s.project_id=p.id AND s.deleted_at IS NULL AND s."group"<>'triage'
   AND a.workspace_id=r.workspace_id AND a.product_id=r.product_id AND a.state='ACTIVE'
   AND a.version=(member->>'association_version')::bigint AND a.provider_installation_id::text=member->>'provider_installation_id'
   AND a.source_project_id=p.id;
  IF NOT FOUND THEN RAISE EXCEPTION 'SCOPE_REOPENING_SOURCE_UNAVAILABLE' USING ERRCODE='23514'; END IF;
  source_digest := curve_sprd_digest(jsonb_build_object('id',src.id::text,'workspace_id',src.workspace_id::text,
   'project_id',src.project_id::text,'parent_id',src.parent_id::text,'state_id',src.state_id::text,
   'created_by_id',src.created_by_id::text,'archived_at',NULL,'deleted_at',NULL,'is_draft','False',
   'updated_at',replace(curve_sprd_instant(src.updated_at),'T',' '),'state_group',src.state_group,
   'state_updated_at',curve_sprd_instant(src.state_updated_at)));
  IF member->>'source_version' IS DISTINCT FROM curve_sprd_instant(src.updated_at)
   OR member->>'source_fingerprint' IS DISTINCT FROM source_digest
   OR (member->>'source_observed_at')::timestamptz>r.recorded_at THEN
   RAISE EXCEPTION 'SCOPE_REOPENING_SOURCE_CHANGED' USING ERRCODE='23514';
  END IF;
  FOREACH actor IN ARRAY reviewers LOOP
   IF NOT EXISTS(SELECT 1 FROM project_members m JOIN projects p ON p.id=m.project_id
    WHERE m.workspace_id=r.workspace_id AND m.project_id=src.project_id AND m.member_id=actor
     AND m.deleted_at IS NULL AND m.is_active AND m.role IN (5,15,20)
     AND (m.role<>5 OR p.guest_view_all_features OR src.created_by_id=actor)) THEN
    RAISE EXCEPTION 'SCOPE_REOPENING_SOURCE_UNAVAILABLE' USING ERRCODE='23514';
   END IF;
  END LOOP;
 END LOOP;
END $$;

CREATE FUNCTION curve_reopen_record_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE init curve_initiative; head curve_scope_proposal; predecessor curve_scope_proposal_revision;
 p jsonb:=NEW.payload; v jsonb:=NEW.payload->'revision'; k text; actor jsonb;
BEGIN
 IF NOT curve_sprd_shape(p,curve_reopen_schema('receipt')) OR octet_length(curve_sprd_canonical(p))>262144
  OR p->>'digest' IS DISTINCT FROM NEW.digest OR curve_sprd_digest(p-'digest') IS DISTINCT FROM NEW.digest THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_RECORD_INVALID' USING ERRCODE='23514';
 END IF;
 FOR k IN SELECT unnest(ARRAY['id','workspace_id','product_id','initiative_id','previous_initiative_version',
  'previous_state','reason_digest','created_by','policy_decision_id','command_receipt_id']) LOOP
  IF to_jsonb(NEW)->k IS DISTINCT FROM p->k THEN
   RAISE EXCEPTION 'SCOPE_REOPENING_RECORD_SUBSTITUTION' USING ERRCODE='23514';
  END IF;
 END LOOP;
 IF NOT isfinite(NEW.recorded_at) OR NEW.recorded_at>clock_timestamp()
  OR (p->>'recorded_at')::timestamptz IS DISTINCT FROM NEW.recorded_at
  OR (p->>'initiative_version')::bigint<>NEW.previous_initiative_version+1
  OR p->>'historical_checkpoint_status' IS DISTINCT FROM (CASE WHEN NEW.previous_checkpoint_id IS NULL THEN 'NONE' ELSE 'RETAINED_STALE' END)
  OR p->'approval_invalidated' IS DISTINCT FROM to_jsonb(EXISTS(SELECT 1 FROM curve_prd_review_decision
   WHERE workspace_id=NEW.workspace_id AND initiative_id=NEW.initiative_id AND id=NEW.previous_decision_id AND state='APPROVED'))
  OR v->>'id' IS DISTINCT FROM NEW.scope_revision_id::text OR v->>'proposal_id' IS DISTINCT FROM NEW.proposal_id::text
  OR v->>'predecessor_id' IS DISTINCT FROM NEW.predecessor_revision_id::text
  OR (v->>'recorded_at')::timestamptz IS DISTINCT FROM NEW.recorded_at
  OR EXISTS(SELECT 1 FROM unnest(ARRAY['workspace_id','product_id','initiative_id','initiative_version','created_by','command_receipt_id']) a
    WHERE v->a IS DISTINCT FROM p->a)
  OR v->'items' IS DISTINCT FROM (SELECT jsonb_agg(m ORDER BY m->>'source_issue_id') FROM jsonb_array_elements(v->'items') m)
  OR (SELECT count(DISTINCT m->>'source_issue_id') FROM jsonb_array_elements(v->'items') m)<>(v->>'item_count')::int
  OR jsonb_array_length(v->'items')<>(v->>'item_count')::int
  OR (SELECT count(*) FROM jsonb_array_elements(v->'items') m WHERE m->>'purpose'='PROPOSED_DELIVERY')<>(v->>'delivery_count')::int
  OR curve_sprd_digest(v->'items') IS DISTINCT FROM v->>'membership_digest' THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_RECEIPT_MISMATCH' USING ERRCODE='23514';
 END IF;
 PERFORM curve_reopen_fence(NEW);
 SELECT * INTO init FROM curve_initiative WHERE workspace_id=NEW.workspace_id AND id=NEW.initiative_id;
 IF ROW(init.version,init.state,init.current_prd_checkpoint_id,init.controlling_prd_decision_id,init.pending_scope_reopening_id)
  IS DISTINCT FROM ROW(NEW.previous_initiative_version,NEW.previous_state,NEW.previous_checkpoint_id,NEW.previous_decision_id,NEW.previous_pending_reopening_id) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_SNAPSHOT_MISMATCH' USING ERRCODE='23514';
 END IF;
 SELECT * INTO head FROM curve_scope_proposal WHERE workspace_id=NEW.workspace_id AND initiative_id=NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR head.id<>NEW.proposal_id OR head.product_id<>NEW.product_id
  OR head.current_revision_id<>NEW.predecessor_revision_id OR head.version+1<>(v->>'version')::bigint THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_PREDECESSOR_MISMATCH' USING ERRCODE='23514';
 END IF;
 SELECT * INTO predecessor FROM curve_scope_proposal_revision WHERE workspace_id=NEW.workspace_id AND id=head.current_revision_id FOR UPDATE;
 IF NOT FOUND OR predecessor.proposal_id<>NEW.proposal_id OR predecessor.initiative_id<>NEW.initiative_id
  OR predecessor.product_id<>NEW.product_id OR predecessor.version<>head.version THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_PREDECESSOR_MISMATCH' USING ERRCODE='23514';
 END IF;
 actor:=jsonb_build_object('actor_type','HUMAN','actor_id',NEW.created_by::text);
 IF NOT EXISTS(SELECT 1 FROM curve_policy_decision WHERE workspace_id=NEW.workspace_id AND id=NEW.policy_decision_id
   AND action='CURVE.SCOPE.REOPEN_AND_REPLACE_SCOPE' AND effect='ALLOW' AND policy_key='CURVE_SCOPE_REOPENING_POLICY'
   AND policy_version=1 AND policy_manifest_digest='sha256:598e492b7dc23369eaf3029d7e208b4fd338d03d3e3388fcb10305e9c02b0094'
   AND resource_type='INITIATIVE' AND resource_id=NEW.initiative_id AND resource_version=NEW.previous_initiative_version
   AND subject=actor AND effective_principal=actor AND curve_sprd_created_here('curve_policy_decision',workspace_id,id)) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_POLICY_REQUIRED' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;

CREATE TRIGGER curve_reopen_immutable BEFORE UPDATE OR DELETE ON curve_scope_reopening FOR EACH ROW EXECUTE FUNCTION curve_prd_immutable();
CREATE TRIGGER curve_reopen_record_guard BEFORE INSERT ON curve_scope_reopening FOR EACH ROW EXECUTE FUNCTION curve_reopen_record_guard();
CREATE TRIGGER curve_reopen_stamp AFTER INSERT ON curve_scope_reopening FOR EACH ROW EXECUTE FUNCTION curve_sprd_stamp();

CREATE FUNCTION curve_reopen_verify_graph(r curve_scope_reopening) RETURNS void LANGUAGE plpgsql AS $$
DECLARE init curve_initiative; rev curve_scope_proposal_revision; e curve_domain_event;
 members jsonb; ref jsonb; v_actor jsonb; v_response_digest text;
BEGIN
 PERFORM curve_reopen_fence(r);
 SELECT * INTO init FROM curve_initiative WHERE workspace_id=r.workspace_id AND id=r.initiative_id;
 IF init.state<>'ALIGNING' OR init.version<>r.previous_initiative_version+1
  OR init.pending_scope_reopening_id IS DISTINCT FROM r.id OR init.controlling_prd_decision_id IS NOT NULL
  OR init.current_prd_checkpoint_id IS DISTINCT FROM r.previous_checkpoint_id
  OR init.updated_by IS DISTINCT FROM jsonb_build_object('actor_type','HUMAN','actor_id',r.created_by::text) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_TRANSITION_INCOMPLETE' USING ERRCODE='23514';
 END IF;
 SELECT * INTO rev FROM curve_scope_proposal_revision WHERE workspace_id=r.workspace_id AND id=r.scope_revision_id;
 IF NOT FOUND OR NOT curve_sprd_created_here('curve_scope_proposal_revision',r.workspace_id,rev.id)
  OR (to_jsonb(rev)-'recorded_at') IS DISTINCT FROM ((r.payload->'revision')-ARRAY['schema_version','recorded_at','items','controlling'])
  OR rev.recorded_at IS DISTINCT FROM r.recorded_at
  OR NOT EXISTS(SELECT 1 FROM curve_scope_proposal WHERE workspace_id=r.workspace_id AND id=r.proposal_id
   AND initiative_id=r.initiative_id AND product_id=r.product_id AND current_revision_id=rev.id AND version=rev.version) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_REVISION_INCOMPLETE' USING ERRCODE='23514';
 END IF;
 SELECT jsonb_agg(jsonb_build_object('association_id',association_id::text,'association_version',association_version,
  'provider_installation_id',provider_installation_id::text,'source_project_id',source_project_id::text,
  'source_issue_id',source_issue_id::text,'purpose',purpose,'source_observed_at',curve_sprd_instant(source_observed_at),
  'source_version',source_version,'source_fingerprint',source_fingerprint) ORDER BY source_issue_id)
  INTO members FROM curve_scope_proposal_item WHERE workspace_id=r.workspace_id AND revision_id=r.scope_revision_id;
 IF members IS DISTINCT FROM r.payload->'revision'->'items' OR curve_sprd_digest(members)<>rev.membership_digest THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_MEMBERS_INCOMPLETE' USING ERRCODE='23514';
 END IF;
 v_actor:=jsonb_build_object('actor_type','HUMAN','actor_id',r.created_by::text);
 SELECT * INTO e FROM curve_domain_event WHERE workspace_id=r.workspace_id AND id=r.command_receipt_id;
 IF NOT FOUND OR e.aggregate_type<>'SCOPE_PROPOSAL' OR e.aggregate_id<>r.proposal_id
  OR e.aggregate_version<>rev.version OR e.sequence<>rev.version OR e.event_type<>'CURVE.SCOPE.REOPENED_AND_REPLACED'
  OR e.payload_schema<>'https://curve.example.invalid/candidates/scope-reopening-v1/scope-reopening-event-v1.schema.json'
  OR e.actor IS DISTINCT FROM v_actor OR e.effective_principal IS DISTINCT FROM v_actor
  OR NOT curve_sprd_shape(e.payload,curve_reopen_schema('event'))
  OR e.payload->>'reopening_id' IS DISTINCT FROM r.id::text OR e.payload->>'reopening_digest' IS DISTINCT FROM r.digest
  OR e.payload->>'initiative_id' IS DISTINCT FROM r.initiative_id::text
  OR e.payload->>'scope_revision_id' IS DISTINCT FROM r.scope_revision_id::text
  OR e.payload->>'policy_decision_id' IS DISTINCT FROM r.policy_decision_id::text
  OR NOT curve_sprd_created_here('curve_domain_event',r.workspace_id,e.id)
  OR NOT EXISTS(SELECT 1 FROM curve_outbox_event WHERE workspace_id=r.workspace_id AND event_id=e.id
    AND destination='CURVE_SCOPE_REOPENING_LOCAL_V1' AND curve_sprd_created_here('curve_outbox_event',workspace_id,id)) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_EVENT_INCOMPLETE' USING ERRCODE='23514';
 END IF;
 ref:=jsonb_build_object('resource_type','SCOPE_REOPENING','resource_id',r.id::text,'resource_version',1);
 v_response_digest:=curve_sprd_digest(jsonb_build_object('response_status',201,'response_resource_ref',ref));
 IF NOT EXISTS(SELECT 1 FROM curve_idempotency_record WHERE workspace_id=r.workspace_id
   AND principal_scope='HUMAN:'||r.created_by::text
   AND command_scope='CURVE.SCOPE.REOPEN_AND_REPLACE_SCOPE:'||r.initiative_id::text
   AND key_digest=e.idempotency_key_digest AND request_digest=r.request_digest
   AND state='COMPLETED' AND response_status=201 AND response_resource_ref=ref AND response_digest=v_response_digest
   AND curve_sprd_created_here('curve_idempotency_record',workspace_id,id))
  OR NOT EXISTS(SELECT 1 FROM curve_audit_event WHERE workspace_id=r.workspace_id
   AND action='CURVE.SCOPE.REOPEN_AND_REPLACE_SCOPE' AND target_type='SCOPE_REOPENING' AND target_id=r.id
   AND target_ref=ref AND outcome='SUCCEEDED' AND actor=v_actor AND effective_principal=v_actor
   AND idempotency_key_digest=e.idempotency_key_digest AND after_digest=v_response_digest
   AND policy_decision_ref=jsonb_build_object('resource_type','POLICY_DECISION','resource_id',r.policy_decision_id::text,'resource_version',1)
   AND curve_sprd_created_here('curve_audit_event',workspace_id,id)) THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_AUDIT_INCOMPLETE' USING ERRCODE='23514';
 END IF;
END $$;
CREATE FUNCTION curve_reopen_commit_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM curve_reopen_verify_graph(NEW);
 RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER curve_reopen_commit AFTER INSERT ON curve_scope_reopening
 DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION curve_reopen_commit_guard();
CREATE TRIGGER curve_reopen_revision_stamp AFTER INSERT ON curve_scope_proposal_revision
 FOR EACH ROW EXECUTE FUNCTION curve_sprd_stamp();
CREATE TRIGGER curve_reopen_idem_stamp AFTER INSERT ON curve_idempotency_record
 FOR EACH ROW EXECUTE FUNCTION curve_sprd_stamp();
CREATE TRIGGER curve_reopen_no_truncate BEFORE TRUNCATE ON curve_scope_reopening
 FOR EACH STATEMENT EXECUTE FUNCTION curve_prd_immutable();
CREATE OR REPLACE FUNCTION curve_guard_scope_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE initiative curve_initiative; head curve_scope_proposal; reopening curve_scope_reopening;
BEGIN
 IF TG_OP <> 'INSERT' THEN
  RAISE EXCEPTION 'Scope revision history is immutable' USING ERRCODE = '23514';
 END IF;

 IF NEW.policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1' THEN
  SELECT * INTO reopening FROM curve_scope_reopening WHERE workspace_id=NEW.workspace_id AND scope_revision_id=NEW.id;
  IF NOT FOUND OR NOT curve_sprd_created_here('curve_scope_reopening',NEW.workspace_id,reopening.id)
   OR (to_jsonb(NEW)-'recorded_at') IS DISTINCT FROM
      ((reopening.payload->'revision')-ARRAY['schema_version','recorded_at','items','controlling'])
   OR NEW.recorded_at IS DISTINCT FROM reopening.recorded_at THEN
   RAISE EXCEPTION 'SCOPE_REOPENING_EXACT_LEDGER_REQUIRED' USING ERRCODE='23514';
  END IF;
  SELECT * INTO initiative FROM curve_initiative WHERE workspace_id=NEW.workspace_id AND id=NEW.initiative_id FOR UPDATE;
  SELECT * INTO head FROM curve_scope_proposal WHERE workspace_id=NEW.workspace_id AND initiative_id=NEW.initiative_id FOR UPDATE;
  IF NOT FOUND OR head.id<>NEW.proposal_id OR head.version+1<>NEW.version OR head.current_revision_id<>NEW.predecessor_id
   OR initiative.version<>reopening.previous_initiative_version OR initiative.state<>reopening.previous_state
   OR initiative.pending_scope_reopening_id IS DISTINCT FROM reopening.previous_pending_reopening_id THEN
   RAISE EXCEPTION 'SCOPE_REOPENING_PREDECESSOR_CHANGED' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
 END IF;
 SELECT * INTO initiative FROM curve_initiative
  WHERE workspace_id = NEW.workspace_id AND id = NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR initiative.product_id <> NEW.product_id OR initiative.mode <> 'STANDALONE'
   OR initiative.state <> 'DRAFT' OR NEW.initiative_version <> initiative.version + 1
   OR NOT EXISTS (SELECT 1 FROM curve_product WHERE workspace_id = NEW.workspace_id
                  AND id = NEW.product_id AND state = 'ACTIVE')
   OR NOT EXISTS (SELECT 1 FROM users WHERE id = NEW.created_by AND is_active AND NOT is_bot)
   OR NOT EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = NEW.workspace_id
                  AND member_id = NEW.created_by AND is_active AND deleted_at IS NULL
                  AND role IN (5, 15, 20) AND (role = 20 OR initiative.creator_user_id = NEW.created_by)) THEN
  RAISE EXCEPTION 'Scope revision requires current Draft authority' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO head FROM curve_scope_proposal
  WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.initiative_id FOR UPDATE;
 IF FOUND THEN
  IF NEW.proposal_id <> head.id OR NEW.version <> head.version + 1
     OR NEW.predecessor_id IS DISTINCT FROM head.current_revision_id THEN
   RAISE EXCEPTION 'Scope revision predecessor/version mismatch' USING ERRCODE = '23514';
  END IF;
 ELSIF NEW.version <> 1 OR NEW.predecessor_id IS NOT NULL THEN
  RAISE EXCEPTION 'Scope revision must start at one' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION curve_guard_scope_head() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE revision curve_scope_proposal_revision; initiative curve_initiative; reopening curve_scope_reopening;
BEGIN
 IF TG_OP = 'DELETE' THEN
  RAISE EXCEPTION 'Scope history cannot be deleted' USING ERRCODE = '23514';
 END IF;

 SELECT * INTO revision FROM curve_scope_proposal_revision WHERE workspace_id=NEW.workspace_id AND id=NEW.current_revision_id;
 IF FOUND AND revision.policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1' THEN
  SELECT * INTO reopening FROM curve_scope_reopening WHERE workspace_id=NEW.workspace_id AND scope_revision_id=revision.id;
  SELECT * INTO initiative FROM curve_initiative WHERE workspace_id=NEW.workspace_id AND id=NEW.initiative_id FOR UPDATE;
  IF TG_OP<>'UPDATE' OR reopening.id IS NULL OR initiative.id IS NULL
   OR NOT curve_sprd_created_here('curve_scope_reopening',NEW.workspace_id,reopening.id)
   OR NOT curve_sprd_created_here('curve_scope_proposal_revision',NEW.workspace_id,revision.id)
   OR ROW(NEW.id,NEW.workspace_id,NEW.initiative_id,NEW.product_id) IS DISTINCT FROM ROW(OLD.id,OLD.workspace_id,OLD.initiative_id,OLD.product_id)
   OR NEW.id<>revision.proposal_id OR NEW.initiative_id<>revision.initiative_id OR NEW.product_id<>revision.product_id
   OR NEW.version<>revision.version OR NEW.version<>OLD.version+1 OR revision.predecessor_id IS DISTINCT FROM OLD.current_revision_id
   OR initiative.state<>'ALIGNING' OR initiative.version<>revision.initiative_version
   OR initiative.pending_scope_reopening_id IS DISTINCT FROM reopening.id OR initiative.controlling_prd_decision_id IS NOT NULL
   OR initiative.current_prd_checkpoint_id IS DISTINCT FROM reopening.previous_checkpoint_id
   OR revision.item_count<>(SELECT count(*) FROM curve_scope_proposal_item WHERE workspace_id=NEW.workspace_id AND revision_id=revision.id)
   OR revision.delivery_count<>(SELECT count(*) FROM curve_scope_proposal_item WHERE workspace_id=NEW.workspace_id AND revision_id=revision.id AND purpose='PROPOSED_DELIVERY') THEN
   RAISE EXCEPTION 'SCOPE_REOPENING_HEAD_INVALID' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
 END IF;
 SELECT * INTO initiative FROM curve_initiative
  WHERE workspace_id = NEW.workspace_id AND id = NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR initiative.product_id <> NEW.product_id OR initiative.mode <> 'STANDALONE'
    OR initiative.state <> 'DRAFT' THEN
  RAISE EXCEPTION 'Scope head requires same-Product Draft Initiative' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO revision FROM curve_scope_proposal_revision
  WHERE workspace_id = NEW.workspace_id AND id = NEW.current_revision_id;
 IF NOT FOUND OR revision.proposal_id <> NEW.id OR revision.initiative_id <> NEW.initiative_id
    OR revision.product_id <> NEW.product_id OR revision.version <> NEW.version
    OR revision.initiative_version <> initiative.version THEN
  RAISE EXCEPTION 'Scope head revision mismatch' USING ERRCODE = '23514';
 END IF;
 IF TG_OP = 'UPDATE' THEN
  IF ROW(NEW.id, NEW.workspace_id, NEW.initiative_id, NEW.product_id)
      IS DISTINCT FROM ROW(OLD.id, OLD.workspace_id, OLD.initiative_id, OLD.product_id)
     OR NEW.version <> OLD.version + 1 OR revision.predecessor_id IS DISTINCT FROM OLD.current_revision_id THEN
   RAISE EXCEPTION 'Scope head cannot rewrite identity or reuse a revision' USING ERRCODE = '23514';
  END IF;
 ELSIF NEW.version <> 1 OR revision.predecessor_id IS NOT NULL THEN
  RAISE EXCEPTION 'Scope head must start at revision one' USING ERRCODE = '23514';
 END IF;
 IF revision.item_count <> (SELECT count(*) FROM curve_scope_proposal_item
                            WHERE workspace_id = NEW.workspace_id AND revision_id = revision.id)
   OR revision.delivery_count <> (SELECT count(*) FROM curve_scope_proposal_item
                                  WHERE workspace_id = NEW.workspace_id AND revision_id = revision.id
                                   AND purpose = 'PROPOSED_DELIVERY') THEN
  RAISE EXCEPTION 'Scope head cannot publish partial members' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION curve_verify_scope_commit() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE reopening curve_scope_reopening;
BEGIN
 IF NEW.policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1' THEN
  SELECT * INTO reopening FROM curve_scope_reopening WHERE workspace_id=NEW.workspace_id AND scope_revision_id=NEW.id;
  IF NOT FOUND OR NOT curve_sprd_created_here('curve_scope_reopening',NEW.workspace_id,reopening.id) THEN
   RAISE EXCEPTION 'SCOPE_REOPENING_EXACT_LEDGER_REQUIRED' USING ERRCODE='23514';
  END IF;
  PERFORM curve_reopen_verify_graph(reopening);
  RETURN NULL;
 END IF;
 IF NOT EXISTS (SELECT 1 FROM curve_scope_proposal WHERE workspace_id = NEW.workspace_id
                AND id = NEW.proposal_id AND initiative_id = NEW.initiative_id
                AND product_id = NEW.product_id AND version >= NEW.version)
   OR NEW.item_count <> (SELECT count(*) FROM curve_scope_proposal_item
                         WHERE workspace_id = NEW.workspace_id AND revision_id = NEW.id)
   OR NEW.delivery_count <> (SELECT count(*) FROM curve_scope_proposal_item
                             WHERE workspace_id = NEW.workspace_id AND revision_id = NEW.id
                              AND purpose = 'PROPOSED_DELIVERY')
   OR NOT EXISTS (SELECT 1 FROM curve_domain_event WHERE workspace_id = NEW.workspace_id
                  AND id = NEW.command_receipt_id AND aggregate_type = 'SCOPE_PROPOSAL'
                  AND aggregate_id = NEW.proposal_id AND aggregate_version = NEW.version)
   OR NOT EXISTS (SELECT 1 FROM curve_outbox_event WHERE workspace_id = NEW.workspace_id
                  AND event_id = NEW.command_receipt_id AND destination = 'CURVE_SCOPE_PROPOSAL_LOCAL_V1') THEN
  RAISE EXCEPTION 'Scope revision must commit its head/members/event/outbox atomically' USING ERRCODE = '23514';
 END IF;
 RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION curve_init_prd_lifecycle_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE checkpoint_record curve_document_checkpoint; decision_record curve_prd_review_decision;
 reopening curve_scope_reopening;
 effective_state text; checkpoint_changed boolean; decision_changed boolean;
BEGIN
 IF TG_OP='INSERT' AND NEW.pending_scope_reopening_id IS NOT NULL THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_EXISTING_INITIATIVE_REQUIRED' USING ERRCODE='23514';
 END IF;
 IF TG_OP='UPDATE' THEN
  IF NEW.pending_scope_reopening_id IS DISTINCT FROM OLD.pending_scope_reopening_id THEN
   IF NEW.pending_scope_reopening_id IS NOT NULL THEN
    SELECT * INTO reopening FROM curve_scope_reopening WHERE workspace_id=NEW.workspace_id
     AND initiative_id=NEW.id AND id=NEW.pending_scope_reopening_id;
    IF NOT FOUND OR NOT curve_sprd_created_here('curve_scope_reopening',NEW.workspace_id,reopening.id)
     OR ROW(OLD.version,OLD.state,OLD.current_prd_checkpoint_id,OLD.controlling_prd_decision_id,OLD.pending_scope_reopening_id)
      IS DISTINCT FROM ROW(reopening.previous_initiative_version,reopening.previous_state,reopening.previous_checkpoint_id,
       reopening.previous_decision_id,reopening.previous_pending_reopening_id)
     OR NEW.state<>'ALIGNING' OR NEW.version<>OLD.version+1 OR NEW.controlling_prd_decision_id IS NOT NULL
     OR NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id
     OR NEW.updated_by IS DISTINCT FROM jsonb_build_object('actor_type','HUMAN','actor_id',reopening.created_by::text)
     OR (to_jsonb(NEW)-ARRAY['state','version','updated_by','updated_at','controlling_prd_decision_id','pending_scope_reopening_id'])
      IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['state','version','updated_by','updated_at','controlling_prd_decision_id','pending_scope_reopening_id'])
     OR NOT EXISTS(SELECT 1 FROM curve_scope_proposal_revision WHERE workspace_id=NEW.workspace_id
      AND initiative_id=NEW.id AND id=reopening.scope_revision_id AND policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1'
      AND curve_sprd_created_here('curve_scope_proposal_revision',workspace_id,id)) THEN
     RAISE EXCEPTION 'SCOPE_REOPENING_TRANSITION_INVALID' USING ERRCODE='23514';
    END IF;
    PERFORM curve_reopen_fence(reopening);
    RETURN NEW;
   ELSE
    IF OLD.state<>'ALIGNING' OR NEW.state<>'PRD_REVIEW' OR NEW.version<>OLD.version+1
     OR NEW.controlling_prd_decision_id IS NOT NULL
     OR NEW.current_prd_checkpoint_id IS NOT DISTINCT FROM OLD.current_prd_checkpoint_id
     OR NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject s JOIN curve_scope_proposal h
       ON h.workspace_id=s.workspace_id AND h.initiative_id=s.initiative_id
      WHERE s.workspace_id=NEW.workspace_id AND s.initiative_id=NEW.id AND s.checkpoint_id=NEW.current_prd_checkpoint_id
       AND s.payload->>'scope_revision_id'=h.current_revision_id::text AND s.payload->>'proposal_id'=h.id::text
       AND (s.payload->>'scope_revision')::bigint=h.version
       AND curve_sprd_created_here('curve_scoped_prd_subject',s.workspace_id,s.id)) THEN
     RAISE EXCEPTION 'SCOPE_REOPENING_FRESH_SCOPED_SUBMISSION_REQUIRED' USING ERRCODE='23514';
    END IF;
    -- Continue into unchanged checkpoint/predecessor/actor lifecycle checks.
   END IF;
  ELSIF NEW.pending_scope_reopening_id IS NOT NULL THEN
   -- Pending scope can pause, resume or cancel under the existing lifecycle.
   -- The retained checkpoint remains stale and never gains gate authority.
   IF NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id
    OR NEW.controlling_prd_decision_id IS NOT NULL
    OR NEW.state NOT IN ('ALIGNING','PAUSED','CANCELLED')
    OR (NEW.state='PAUSED' AND NEW.paused_from_state IS DISTINCT FROM 'ALIGNING') THEN
    RAISE EXCEPTION 'SCOPE_REOPENING_FRESH_SCOPED_SUBMISSION_REQUIRED' USING ERRCODE='23514';
   END IF;
   IF ROW(NEW.state,NEW.paused_from_state) IS DISTINCT FROM ROW(OLD.state,OLD.paused_from_state) THEN
    IF NEW.version<>OLD.version+1 OR NOT (
      (OLD.state='ALIGNING' AND NEW.state='PAUSED' AND NEW.paused_from_state='ALIGNING') OR
      (OLD.state='PAUSED' AND OLD.paused_from_state='ALIGNING' AND NEW.state='ALIGNING') OR
      (OLD.state IN ('ALIGNING','PAUSED') AND NEW.state='CANCELLED')
    ) THEN
     RAISE EXCEPTION 'PRD_LIFECYCLE_TRANSITION_INVALID' USING ERRCODE='23514';
    END IF;
   END IF;
   RETURN NEW;
  END IF;
 END IF;

 effective_state := CASE WHEN NEW.state = 'PAUSED' THEN NEW.paused_from_state ELSE NEW.state END;
 IF NEW.current_prd_checkpoint_id IS NULL THEN
  IF NEW.controlling_prd_decision_id IS NOT NULL OR effective_state IN ('PRD_REVIEW', 'PLANNING') THEN
   RAISE EXCEPTION 'PRD_SUBMITTED_CHECKPOINT_REQUIRED' USING ERRCODE = '23514';
  END IF;
 ELSE
  SELECT * INTO checkpoint_record FROM curve_document_checkpoint
   WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.id AND id = NEW.current_prd_checkpoint_id;
  IF NOT FOUND THEN
   RAISE EXCEPTION 'PRD_CURRENT_CHECKPOINT_SCOPE_INVALID' USING ERRCODE = '23514';
  END IF;
  IF effective_state = 'DRAFT' THEN
   RAISE EXCEPTION 'PRD_DRAFT_CANNOT_HAVE_SUBMISSION' USING ERRCODE = '23514';
  END IF;
  IF NEW.controlling_prd_decision_id IS NOT NULL THEN
   SELECT * INTO decision_record FROM curve_prd_review_decision
    WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.id AND id = NEW.controlling_prd_decision_id;
   IF NOT FOUND OR decision_record.checkpoint_id <> NEW.current_prd_checkpoint_id THEN
    RAISE EXCEPTION 'PRD_CONTROLLING_DECISION_SUBJECT_INVALID' USING ERRCODE = '23514';
   END IF;
  END IF;
  IF effective_state = 'PRD_REVIEW' AND NEW.controlling_prd_decision_id IS NOT NULL THEN
   RAISE EXCEPTION 'PRD_REVIEW_REQUIRES_UNDECIDED_SUBMISSION' USING ERRCODE = '23514';
  END IF;
  IF effective_state = 'PLANNING' AND
     (NEW.controlling_prd_decision_id IS NULL OR decision_record.state IS DISTINCT FROM 'APPROVED') THEN
   RAISE EXCEPTION 'PRD_PLANNING_REQUIRES_APPROVAL' USING ERRCODE = '23514';
  END IF;
  IF effective_state = 'ALIGNING' AND
     (NEW.controlling_prd_decision_id IS NULL OR decision_record.state NOT IN ('CHANGES_REQUESTED', 'REJECTED')) THEN
   RAISE EXCEPTION 'PRD_ALIGNMENT_REQUIRES_REVIEW_RETURN' USING ERRCODE = '23514';
  END IF;
 END IF;
 IF TG_OP = 'INSERT' THEN RETURN NEW; END IF;
 checkpoint_changed := NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id;
 decision_changed := NEW.controlling_prd_decision_id IS DISTINCT FROM OLD.controlling_prd_decision_id;
 IF OLD.current_prd_checkpoint_id IS NULL AND NOT checkpoint_changed AND NOT decision_changed THEN RETURN NEW; END IF;
 IF NEW.current_prd_checkpoint_id IS NULL THEN
  RAISE EXCEPTION 'PRD_SUBMISSION_HISTORY_RETAINED' USING ERRCODE = '23514';
 END IF;
 IF checkpoint_changed OR decision_changed OR
    ROW(NEW.state, NEW.paused_from_state) IS DISTINCT FROM ROW(OLD.state, OLD.paused_from_state) THEN
  IF NEW.version <> OLD.version + 1 THEN
   RAISE EXCEPTION 'PRD_TRANSITION_VERSION_INVALID' USING ERRCODE = '23514';
  END IF;
  IF checkpoint_changed THEN
   IF OLD.state NOT IN ('ALIGNING', 'PRD_REVIEW') OR NEW.state <> 'PRD_REVIEW' OR
      NEW.controlling_prd_decision_id IS NOT NULL OR
      checkpoint_record.predecessor_id IS DISTINCT FROM OLD.current_prd_checkpoint_id OR
      NEW.updated_by->>'actor_type' IS DISTINCT FROM 'HUMAN' OR
      NEW.updated_by IS DISTINCT FROM checkpoint_record.submitted_or_approved_by OR
      EXISTS (SELECT 1 FROM curve_document_checkpoint
       WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.id
        AND checkpoint_number > checkpoint_record.checkpoint_number) THEN
    RAISE EXCEPTION 'PRD_SUBMISSION_TRANSITION_INVALID' USING ERRCODE = '23514';
   END IF;
  ELSIF decision_changed THEN
   IF OLD.state <> 'PRD_REVIEW' OR NEW.controlling_prd_decision_id IS NULL OR
      OLD.controlling_prd_decision_id IS NOT NULL OR
      NEW.updated_by IS DISTINCT FROM decision_record.decided_by OR
      NEW.state IS DISTINCT FROM
       (CASE WHEN decision_record.state = 'APPROVED' THEN 'PLANNING' ELSE 'ALIGNING' END) THEN
    RAISE EXCEPTION 'PRD_DECISION_TRANSITION_INVALID' USING ERRCODE = '23514';
   END IF;
  ELSIF NOT (
    (OLD.state IN ('ALIGNING', 'PRD_REVIEW', 'PLANNING') AND NEW.state = 'PAUSED'
      AND NEW.paused_from_state = OLD.state) OR
    (OLD.state = 'PAUSED' AND NEW.state = OLD.paused_from_state) OR
    (OLD.state IN ('ALIGNING', 'PRD_REVIEW', 'PLANNING', 'PAUSED') AND NEW.state = 'CANCELLED')
  ) THEN
   RAISE EXCEPTION 'PRD_LIFECYCLE_TRANSITION_INVALID' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION curve_scope_prd_transition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.pending_scope_reopening_id IS NOT NULL AND NEW.controlling_prd_decision_id IS NOT NULL THEN
  RAISE EXCEPTION 'SCOPE_REOPENING_FRESH_SCOPED_SUBMISSION_REQUIRED' USING ERRCODE='23514';
 END IF;
 IF NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id
  AND EXISTS(SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
   ON i.workspace_id=h.workspace_id AND i.revision_id=h.current_revision_id
   WHERE h.workspace_id=NEW.workspace_id AND h.initiative_id=NEW.id AND (i.purpose='PROPOSED_DELIVERY' OR EXISTS(SELECT 1 FROM curve_scope_proposal_revision r WHERE r.workspace_id=h.workspace_id AND r.id=h.current_revision_id AND r.policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1')))
  AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject s WHERE s.workspace_id=NEW.workspace_id
   AND s.initiative_id=NEW.id AND s.checkpoint_id=NEW.current_prd_checkpoint_id
   AND curve_sprd_created_here('curve_scoped_prd_subject',s.workspace_id,s.id)) THEN
  RAISE EXCEPTION 'PRD_SCOPE_BRIDGE_UNAVAILABLE' USING ERRCODE='23514';
 END IF;
 IF NEW.controlling_prd_decision_id IS DISTINCT FROM OLD.controlling_prd_decision_id
  AND NEW.controlling_prd_decision_id IS NOT NULL
  AND (EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
      AND initiative_id=NEW.id AND checkpoint_id=NEW.current_prd_checkpoint_id)
   OR (EXISTS(SELECT 1 FROM curve_prd_review_decision WHERE workspace_id=NEW.workspace_id
       AND initiative_id=NEW.id AND id=NEW.controlling_prd_decision_id AND state='APPROVED')
    AND EXISTS(SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
     ON i.workspace_id=h.workspace_id AND i.revision_id=h.current_revision_id
     WHERE h.workspace_id=NEW.workspace_id AND h.initiative_id=NEW.id AND (i.purpose='PROPOSED_DELIVERY' OR EXISTS(SELECT 1 FROM curve_scope_proposal_revision r WHERE r.workspace_id=h.workspace_id AND r.id=h.current_revision_id AND r.policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1')))))
  AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_decision d WHERE d.workspace_id=NEW.workspace_id
   AND d.initiative_id=NEW.id AND d.decision_id=NEW.controlling_prd_decision_id
   AND curve_sprd_created_here('curve_scoped_prd_decision',d.workspace_id,d.id)) THEN
  RAISE EXCEPTION 'PRD_SCOPE_BRIDGE_UNAVAILABLE' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION curve_sprd_verify_commit() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE op curve_operation; cmd curve_scoped_prd_accepted_command; s curve_scoped_prd_subject;
 d curve_scoped_prd_decision; init curve_initiative; completion_operation_id uuid; event curve_domain_event;
 policy curve_policy_decision; audit curve_audit_event;
BEGIN
 IF TG_TABLE_NAME='curve_scoped_prd_observation' THEN
  SELECT * INTO event FROM curve_domain_event WHERE workspace_id=NEW.workspace_id
   AND aggregate_type='SCOPED_PRD_OBSERVATION' AND aggregate_id=NEW.id AND aggregate_version=1 AND sequence=1;
  IF NOT FOUND OR event.event_type<>'CURVE.SCOPED_PRD.OBSERVATION_RECORDED'
   OR NOT curve_sprd_shape(event.payload,curve_sprd_schema('observed-event'))
   OR event.payload->>'observation_id'<>NEW.id::text OR event.payload->>'observation_digest'<>NEW.digest
   OR event.payload->>'initiative_id'<>NEW.initiative_id::text
   OR event.actor IS DISTINCT FROM jsonb_build_object('actor_type','HUMAN','actor_id',NEW.created_by::text)
   OR event.effective_principal IS DISTINCT FROM event.actor
   OR NOT curve_sprd_created_here('curve_domain_event',NEW.workspace_id,event.id)
   OR NOT EXISTS(SELECT 1 FROM curve_outbox_event WHERE workspace_id=NEW.workspace_id AND event_id=event.id
      AND destination='CURVE_SCOPED_PRD_METADATA_V1' AND curve_sprd_created_here('curve_outbox_event',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_OBSERVATION_EVENT_REQUIRED' USING ERRCODE='23514';
  END IF;
  SELECT * INTO policy FROM curve_policy_decision WHERE workspace_id=NEW.workspace_id
   AND id=(event.payload->>'policy_decision_id')::uuid;
  IF NOT FOUND OR policy.action<>'CURVE.PRD.SUBMIT' OR policy.effect<>'ALLOW' OR policy.policy_key<>'CURVE_PRD_POLICY'
   OR policy.resource_type<>'INITIATIVE' OR policy.resource_id<>NEW.initiative_id
   OR policy.resource_version<>(NEW.payload->>'initiative_version')::bigint
   OR policy.subject IS DISTINCT FROM event.actor OR policy.effective_principal IS DISTINCT FROM event.actor
   OR NOT curve_sprd_created_here('curve_policy_decision',NEW.workspace_id,policy.id)
   OR NOT EXISTS(SELECT 1 FROM curve_audit_event WHERE workspace_id=NEW.workspace_id
      AND target_type='SCOPED_PRD_OBSERVATION' AND target_id=NEW.id AND outcome='SUCCEEDED'
      AND action='CURVE.SCOPED_PRD.OBSERVE' AND actor=event.actor
      AND policy_decision_ref=jsonb_build_object('resource_type','POLICY_DECISION','resource_id',policy.id::text,'resource_version',1)
      AND curve_sprd_created_here('curve_audit_event',workspace_id,id))
   OR NOT EXISTS(SELECT 1 FROM curve_idempotency_record WHERE workspace_id=NEW.workspace_id
      AND principal_scope='HUMAN:'||NEW.created_by::text
      AND command_scope='SCOPED_PRD_V1_OBSERVE:'||NEW.initiative_id::text
      AND key_digest=event.idempotency_key_digest AND state='COMPLETED' AND response_status=201
      AND response_resource_ref=jsonb_build_object('resource_type','SCOPED_PRD_OBSERVATION','resource_id',NEW.id::text,'resource_version',1)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_OBSERVATION_AUDIT_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_document_checkpoint' THEN
  IF EXISTS(SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
    ON i.workspace_id=h.workspace_id AND i.revision_id=h.current_revision_id
    WHERE h.workspace_id=NEW.workspace_id AND h.initiative_id=NEW.initiative_id AND (i.purpose='PROPOSED_DELIVERY' OR EXISTS(SELECT 1 FROM curve_scope_proposal_revision r WHERE r.workspace_id=h.workspace_id AND r.id=h.current_revision_id AND r.policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1')))
   AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
    AND initiative_id=NEW.initiative_id AND checkpoint_id=NEW.id
    AND curve_sprd_created_here('curve_scoped_prd_subject',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_CHECKPOINT_SIDECAR_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_prd_review_decision' THEN
  IF EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
    AND initiative_id=NEW.initiative_id AND checkpoint_id=NEW.checkpoint_id)
   AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_decision WHERE workspace_id=NEW.workspace_id
    AND initiative_id=NEW.initiative_id AND decision_id=NEW.id
    AND curve_sprd_created_here('curve_scoped_prd_decision',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_DECISION_SIDECAR_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_readiness' THEN
  IF NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
   AND initiative_id=NEW.initiative_id AND scoped_readiness_id=NEW.id
   AND curve_sprd_created_here('curve_scoped_prd_subject',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_READINESS_SUBJECT_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_subject' THEN completion_operation_id:=NEW.submission_operation_id;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_decision' THEN completion_operation_id:=NEW.review_operation_id;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_accepted_command' THEN completion_operation_id:=NEW.operation_id;
 ELSE
  IF NEW.command_type NOT LIKE 'SCOPED_PRD_V1_%' THEN RETURN NULL; END IF;
  completion_operation_id:=NEW.id;
 END IF;
 SELECT * INTO op FROM curve_operation WHERE workspace_id=NEW.workspace_id AND id=completion_operation_id;
 SELECT * INTO cmd FROM curve_scoped_prd_accepted_command WHERE workspace_id=NEW.workspace_id AND operation_id=op.id;
 IF NOT FOUND OR op.command_type<>replace(cmd.action,'CURVE.PRD.','SCOPED_PRD_V1_') THEN
  RAISE EXCEPTION 'SCOPED_PRD_OPERATION_COMMAND_REQUIRED' USING ERRCODE='23514';
 END IF;
 IF TG_TABLE_NAME IN ('curve_scoped_prd_subject','curve_scoped_prd_decision') AND op.status<>'SUCCEEDED' THEN
  RAISE EXCEPTION 'SCOPED_PRD_ATOMIC_COMPLETION_REQUIRED' USING ERRCODE='23514';
 END IF;
 IF op.status<>'SUCCEEDED' THEN RETURN NULL; END IF;
 IF NOT EXISTS(SELECT 1 FROM curve_domain_event e JOIN curve_outbox_event o
   ON o.workspace_id=e.workspace_id AND o.event_id=e.id
   WHERE e.workspace_id=op.workspace_id AND e.aggregate_type='OPERATION' AND e.aggregate_id=op.id
    AND e.aggregate_version=op.aggregate_version AND e.event_type='curve.operation.state_changed'
    AND e.payload->>'status'='SUCCEEDED' AND o.destination='CURVE_SCOPED_PRD_CANDIDATE_V1'
    AND curve_sprd_created_here('curve_domain_event',e.workspace_id,e.id)
    AND curve_sprd_created_here('curve_outbox_event',o.workspace_id,o.id))
  OR NOT EXISTS(SELECT 1 FROM curve_audit_event a JOIN curve_policy_decision p
    ON p.workspace_id=a.workspace_id AND p.id::text=a.policy_decision_ref->>'resource_id'
   WHERE a.workspace_id=op.workspace_id AND a.action=cmd.action||'.COMPLETION' AND a.outcome='SUCCEEDED'
    AND a.target_type='INITIATIVE' AND a.target_id=cmd.initiative_id AND a.target_ref=op.result_ref
    AND a.actor=op.created_by AND a.causation_id=op.id::text
    AND p.action=cmd.action AND p.effect='ALLOW' AND p.policy_key='CURVE_PRD_POLICY'
    AND p.resource_type='INITIATIVE' AND p.resource_id=cmd.initiative_id AND p.resource_version=cmd.expected_version
    AND p.subject=op.created_by AND p.effective_principal=op.created_by
    AND curve_sprd_created_here('curve_audit_event',a.workspace_id,a.id)
    AND curve_sprd_created_here('curve_policy_decision',p.workspace_id,p.id)) THEN
  RAISE EXCEPTION 'SCOPED_PRD_ATOMIC_AUDIT_REQUIRED' USING ERRCODE='23514';
 END IF;
 SELECT * INTO init FROM curve_initiative WHERE workspace_id=op.workspace_id AND id=cmd.initiative_id;
 IF op.result_ref IS DISTINCT FROM jsonb_build_object('resource_type','INITIATIVE','resource_id',cmd.initiative_id::text,
    'resource_version',cmd.expected_version+1) THEN
  RAISE EXCEPTION 'SCOPED_PRD_OPERATION_RESULT_MISMATCH' USING ERRCODE='23514';
 END IF;
 IF cmd.action='CURVE.PRD.SUBMIT' THEN
  SELECT * INTO s FROM curve_scoped_prd_subject WHERE workspace_id=op.workspace_id
   AND initiative_id=cmd.initiative_id AND submission_operation_id=op.id;
  IF NOT FOUND OR NOT curve_sprd_created_here('curve_scoped_prd_subject',s.workspace_id,s.id)
   OR init.current_prd_checkpoint_id IS DISTINCT FROM s.checkpoint_id OR init.version<>cmd.expected_version+1
   OR init.state<>'PRD_REVIEW' OR init.controlling_prd_decision_id IS NOT NULL OR init.pending_scope_reopening_id IS NOT NULL THEN
   RAISE EXCEPTION 'SCOPED_PRD_SUBMISSION_INCOMPLETE' USING ERRCODE='23514';
  END IF;
 ELSE
  SELECT * INTO d FROM curve_scoped_prd_decision WHERE workspace_id=op.workspace_id
   AND initiative_id=cmd.initiative_id AND review_operation_id=op.id;
  IF NOT FOUND OR NOT curve_sprd_created_here('curve_scoped_prd_decision',d.workspace_id,d.id)
   OR init.controlling_prd_decision_id IS DISTINCT FROM d.decision_id OR init.version<>cmd.expected_version+1
   OR init.state IS DISTINCT FROM (CASE WHEN cmd.action='CURVE.PRD.APPROVE' THEN 'PLANNING' ELSE 'ALIGNING' END) THEN
   RAISE EXCEPTION 'SCOPED_PRD_REVIEW_INCOMPLETE' USING ERRCODE='23514';
  END IF;
 END IF;
 RETURN NULL;
END $$;"""
REVERSE_GUARDS = r"""
LOCK TABLE curve_scope_reopening,curve_initiative,curve_scope_proposal_revision,
 curve_policy_decision,curve_audit_event,curve_domain_event,curve_outbox_event,curve_idempotency_record IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM curve_scope_reopening) OR EXISTS(SELECT 1 FROM curve_initiative WHERE pending_scope_reopening_id IS NOT NULL)
  OR EXISTS(SELECT 1 FROM curve_scope_proposal_revision WHERE policy_edition='REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1')
  OR EXISTS(SELECT 1 FROM curve_policy_decision WHERE policy_key='CURVE_SCOPE_REOPENING_POLICY')
  OR EXISTS(SELECT 1 FROM curve_audit_event WHERE action='CURVE.SCOPE.REOPEN_AND_REPLACE_SCOPE')
  OR EXISTS(SELECT 1 FROM curve_domain_event WHERE event_type='CURVE.SCOPE.REOPENED_AND_REPLACED')
  OR EXISTS(SELECT 1 FROM curve_outbox_event WHERE destination='CURVE_SCOPE_REOPENING_LOCAL_V1')
  OR EXISTS(SELECT 1 FROM curve_idempotency_record WHERE command_scope LIKE 'CURVE.SCOPE.REOPEN_AND_REPLACE_SCOPE:%') THEN
  RAISE EXCEPTION 'Retained scope reopening evidence requires a preservation migration' USING ERRCODE='23514';
 END IF;
END $$;
CREATE OR REPLACE FUNCTION curve_init_prd_lifecycle_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE checkpoint_record curve_document_checkpoint; decision_record curve_prd_review_decision;
 effective_state text; checkpoint_changed boolean; decision_changed boolean;
BEGIN
 effective_state := CASE WHEN NEW.state = 'PAUSED' THEN NEW.paused_from_state ELSE NEW.state END;
 IF NEW.current_prd_checkpoint_id IS NULL THEN
  IF NEW.controlling_prd_decision_id IS NOT NULL OR effective_state IN ('PRD_REVIEW', 'PLANNING') THEN
   RAISE EXCEPTION 'PRD_SUBMITTED_CHECKPOINT_REQUIRED' USING ERRCODE = '23514';
  END IF;
 ELSE
  SELECT * INTO checkpoint_record FROM curve_document_checkpoint
   WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.id AND id = NEW.current_prd_checkpoint_id;
  IF NOT FOUND THEN
   RAISE EXCEPTION 'PRD_CURRENT_CHECKPOINT_SCOPE_INVALID' USING ERRCODE = '23514';
  END IF;
  IF effective_state = 'DRAFT' THEN
   RAISE EXCEPTION 'PRD_DRAFT_CANNOT_HAVE_SUBMISSION' USING ERRCODE = '23514';
  END IF;
  IF NEW.controlling_prd_decision_id IS NOT NULL THEN
   SELECT * INTO decision_record FROM curve_prd_review_decision
    WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.id AND id = NEW.controlling_prd_decision_id;
   IF NOT FOUND OR decision_record.checkpoint_id <> NEW.current_prd_checkpoint_id THEN
    RAISE EXCEPTION 'PRD_CONTROLLING_DECISION_SUBJECT_INVALID' USING ERRCODE = '23514';
   END IF;
  END IF;
  IF effective_state = 'PRD_REVIEW' AND NEW.controlling_prd_decision_id IS NOT NULL THEN
   RAISE EXCEPTION 'PRD_REVIEW_REQUIRES_UNDECIDED_SUBMISSION' USING ERRCODE = '23514';
  END IF;
  IF effective_state = 'PLANNING' AND
     (NEW.controlling_prd_decision_id IS NULL OR decision_record.state IS DISTINCT FROM 'APPROVED') THEN
   RAISE EXCEPTION 'PRD_PLANNING_REQUIRES_APPROVAL' USING ERRCODE = '23514';
  END IF;
  IF effective_state = 'ALIGNING' AND
     (NEW.controlling_prd_decision_id IS NULL OR decision_record.state NOT IN ('CHANGES_REQUESTED', 'REJECTED')) THEN
   RAISE EXCEPTION 'PRD_ALIGNMENT_REQUIRES_REVIEW_RETURN' USING ERRCODE = '23514';
  END IF;
 END IF;
 IF TG_OP = 'INSERT' THEN RETURN NEW; END IF;
 checkpoint_changed := NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id;
 decision_changed := NEW.controlling_prd_decision_id IS DISTINCT FROM OLD.controlling_prd_decision_id;
 IF OLD.current_prd_checkpoint_id IS NULL AND NOT checkpoint_changed AND NOT decision_changed THEN RETURN NEW; END IF;
 IF NEW.current_prd_checkpoint_id IS NULL THEN
  RAISE EXCEPTION 'PRD_SUBMISSION_HISTORY_RETAINED' USING ERRCODE = '23514';
 END IF;
 IF checkpoint_changed OR decision_changed OR
    ROW(NEW.state, NEW.paused_from_state) IS DISTINCT FROM ROW(OLD.state, OLD.paused_from_state) THEN
  IF NEW.version <> OLD.version + 1 THEN
   RAISE EXCEPTION 'PRD_TRANSITION_VERSION_INVALID' USING ERRCODE = '23514';
  END IF;
  IF checkpoint_changed THEN
   IF OLD.state NOT IN ('ALIGNING', 'PRD_REVIEW') OR NEW.state <> 'PRD_REVIEW' OR
      NEW.controlling_prd_decision_id IS NOT NULL OR
      checkpoint_record.predecessor_id IS DISTINCT FROM OLD.current_prd_checkpoint_id OR
      NEW.updated_by->>'actor_type' IS DISTINCT FROM 'HUMAN' OR
      NEW.updated_by IS DISTINCT FROM checkpoint_record.submitted_or_approved_by OR
      EXISTS (SELECT 1 FROM curve_document_checkpoint
       WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.id
        AND checkpoint_number > checkpoint_record.checkpoint_number) THEN
    RAISE EXCEPTION 'PRD_SUBMISSION_TRANSITION_INVALID' USING ERRCODE = '23514';
   END IF;
  ELSIF decision_changed THEN
   IF OLD.state <> 'PRD_REVIEW' OR NEW.controlling_prd_decision_id IS NULL OR
      OLD.controlling_prd_decision_id IS NOT NULL OR
      NEW.updated_by IS DISTINCT FROM decision_record.decided_by OR
      NEW.state IS DISTINCT FROM
       (CASE WHEN decision_record.state = 'APPROVED' THEN 'PLANNING' ELSE 'ALIGNING' END) THEN
    RAISE EXCEPTION 'PRD_DECISION_TRANSITION_INVALID' USING ERRCODE = '23514';
   END IF;
  ELSIF NOT (
    (OLD.state IN ('ALIGNING', 'PRD_REVIEW', 'PLANNING') AND NEW.state = 'PAUSED'
      AND NEW.paused_from_state = OLD.state) OR
    (OLD.state = 'PAUSED' AND NEW.state = OLD.paused_from_state) OR
    (OLD.state IN ('ALIGNING', 'PRD_REVIEW', 'PLANNING', 'PAUSED') AND NEW.state = 'CANCELLED')
  ) THEN
   RAISE EXCEPTION 'PRD_LIFECYCLE_TRANSITION_INVALID' USING ERRCODE = '23514';
  END IF;
 END IF;
 RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION curve_guard_scope_revision() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE initiative curve_initiative; head curve_scope_proposal;
BEGIN
 IF TG_OP <> 'INSERT' THEN
  RAISE EXCEPTION 'Scope revision history is immutable' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO initiative FROM curve_initiative
  WHERE workspace_id = NEW.workspace_id AND id = NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR initiative.product_id <> NEW.product_id OR initiative.mode <> 'STANDALONE'
   OR initiative.state <> 'DRAFT' OR NEW.initiative_version <> initiative.version + 1
   OR NOT EXISTS (SELECT 1 FROM curve_product WHERE workspace_id = NEW.workspace_id
                  AND id = NEW.product_id AND state = 'ACTIVE')
   OR NOT EXISTS (SELECT 1 FROM users WHERE id = NEW.created_by AND is_active AND NOT is_bot)
   OR NOT EXISTS (SELECT 1 FROM workspace_members WHERE workspace_id = NEW.workspace_id
                  AND member_id = NEW.created_by AND is_active AND deleted_at IS NULL
                  AND role IN (5, 15, 20) AND (role = 20 OR initiative.creator_user_id = NEW.created_by)) THEN
  RAISE EXCEPTION 'Scope revision requires current Draft authority' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO head FROM curve_scope_proposal
  WHERE workspace_id = NEW.workspace_id AND initiative_id = NEW.initiative_id FOR UPDATE;
 IF FOUND THEN
  IF NEW.proposal_id <> head.id OR NEW.version <> head.version + 1
     OR NEW.predecessor_id IS DISTINCT FROM head.current_revision_id THEN
   RAISE EXCEPTION 'Scope revision predecessor/version mismatch' USING ERRCODE = '23514';
  END IF;
 ELSIF NEW.version <> 1 OR NEW.predecessor_id IS NOT NULL THEN
  RAISE EXCEPTION 'Scope revision must start at one' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION curve_guard_scope_head() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE revision curve_scope_proposal_revision; initiative curve_initiative;
BEGIN
 IF TG_OP = 'DELETE' THEN
  RAISE EXCEPTION 'Scope history cannot be deleted' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO initiative FROM curve_initiative
  WHERE workspace_id = NEW.workspace_id AND id = NEW.initiative_id FOR UPDATE;
 IF NOT FOUND OR initiative.product_id <> NEW.product_id OR initiative.mode <> 'STANDALONE'
    OR initiative.state <> 'DRAFT' THEN
  RAISE EXCEPTION 'Scope head requires same-Product Draft Initiative' USING ERRCODE = '23514';
 END IF;
 SELECT * INTO revision FROM curve_scope_proposal_revision
  WHERE workspace_id = NEW.workspace_id AND id = NEW.current_revision_id;
 IF NOT FOUND OR revision.proposal_id <> NEW.id OR revision.initiative_id <> NEW.initiative_id
    OR revision.product_id <> NEW.product_id OR revision.version <> NEW.version
    OR revision.initiative_version <> initiative.version THEN
  RAISE EXCEPTION 'Scope head revision mismatch' USING ERRCODE = '23514';
 END IF;
 IF TG_OP = 'UPDATE' THEN
  IF ROW(NEW.id, NEW.workspace_id, NEW.initiative_id, NEW.product_id)
      IS DISTINCT FROM ROW(OLD.id, OLD.workspace_id, OLD.initiative_id, OLD.product_id)
     OR NEW.version <> OLD.version + 1 OR revision.predecessor_id IS DISTINCT FROM OLD.current_revision_id THEN
   RAISE EXCEPTION 'Scope head cannot rewrite identity or reuse a revision' USING ERRCODE = '23514';
  END IF;
 ELSIF NEW.version <> 1 OR revision.predecessor_id IS NOT NULL THEN
  RAISE EXCEPTION 'Scope head must start at revision one' USING ERRCODE = '23514';
 END IF;
 IF revision.item_count <> (SELECT count(*) FROM curve_scope_proposal_item
                            WHERE workspace_id = NEW.workspace_id AND revision_id = revision.id)
   OR revision.delivery_count <> (SELECT count(*) FROM curve_scope_proposal_item
                                  WHERE workspace_id = NEW.workspace_id AND revision_id = revision.id
                                   AND purpose = 'PROPOSED_DELIVERY') THEN
  RAISE EXCEPTION 'Scope head cannot publish partial members' USING ERRCODE = '23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION curve_verify_scope_commit() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM curve_scope_proposal WHERE workspace_id = NEW.workspace_id
                AND id = NEW.proposal_id AND initiative_id = NEW.initiative_id
                AND product_id = NEW.product_id AND version >= NEW.version)
   OR NEW.item_count <> (SELECT count(*) FROM curve_scope_proposal_item
                         WHERE workspace_id = NEW.workspace_id AND revision_id = NEW.id)
   OR NEW.delivery_count <> (SELECT count(*) FROM curve_scope_proposal_item
                             WHERE workspace_id = NEW.workspace_id AND revision_id = NEW.id
                              AND purpose = 'PROPOSED_DELIVERY')
   OR NOT EXISTS (SELECT 1 FROM curve_domain_event WHERE workspace_id = NEW.workspace_id
                  AND id = NEW.command_receipt_id AND aggregate_type = 'SCOPE_PROPOSAL'
                  AND aggregate_id = NEW.proposal_id AND aggregate_version = NEW.version)
   OR NOT EXISTS (SELECT 1 FROM curve_outbox_event WHERE workspace_id = NEW.workspace_id
                  AND event_id = NEW.command_receipt_id AND destination = 'CURVE_SCOPE_PROPOSAL_LOCAL_V1') THEN
  RAISE EXCEPTION 'Scope revision must commit its head/members/event/outbox atomically' USING ERRCODE = '23514';
 END IF;
 RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION curve_scope_prd_transition_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.current_prd_checkpoint_id IS DISTINCT FROM OLD.current_prd_checkpoint_id
  AND EXISTS(SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
   ON i.workspace_id=h.workspace_id AND i.revision_id=h.current_revision_id
   WHERE h.workspace_id=NEW.workspace_id AND h.initiative_id=NEW.id AND i.purpose='PROPOSED_DELIVERY')
  AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject s WHERE s.workspace_id=NEW.workspace_id
   AND s.initiative_id=NEW.id AND s.checkpoint_id=NEW.current_prd_checkpoint_id
   AND curve_sprd_created_here('curve_scoped_prd_subject',s.workspace_id,s.id)) THEN
  RAISE EXCEPTION 'PRD_SCOPE_BRIDGE_UNAVAILABLE' USING ERRCODE='23514';
 END IF;
 IF NEW.controlling_prd_decision_id IS DISTINCT FROM OLD.controlling_prd_decision_id
  AND NEW.controlling_prd_decision_id IS NOT NULL
  AND (EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
      AND initiative_id=NEW.id AND checkpoint_id=NEW.current_prd_checkpoint_id)
   OR (EXISTS(SELECT 1 FROM curve_prd_review_decision WHERE workspace_id=NEW.workspace_id
       AND initiative_id=NEW.id AND id=NEW.controlling_prd_decision_id AND state='APPROVED')
    AND EXISTS(SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
     ON i.workspace_id=h.workspace_id AND i.revision_id=h.current_revision_id
     WHERE h.workspace_id=NEW.workspace_id AND h.initiative_id=NEW.id AND i.purpose='PROPOSED_DELIVERY')))
  AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_decision d WHERE d.workspace_id=NEW.workspace_id
   AND d.initiative_id=NEW.id AND d.decision_id=NEW.controlling_prd_decision_id
   AND curve_sprd_created_here('curve_scoped_prd_decision',d.workspace_id,d.id)) THEN
  RAISE EXCEPTION 'PRD_SCOPE_BRIDGE_UNAVAILABLE' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION curve_sprd_verify_commit() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE op curve_operation; cmd curve_scoped_prd_accepted_command; s curve_scoped_prd_subject;
 d curve_scoped_prd_decision; init curve_initiative; completion_operation_id uuid; event curve_domain_event;
 policy curve_policy_decision; audit curve_audit_event;
BEGIN
 IF TG_TABLE_NAME='curve_scoped_prd_observation' THEN
  SELECT * INTO event FROM curve_domain_event WHERE workspace_id=NEW.workspace_id
   AND aggregate_type='SCOPED_PRD_OBSERVATION' AND aggregate_id=NEW.id AND aggregate_version=1 AND sequence=1;
  IF NOT FOUND OR event.event_type<>'CURVE.SCOPED_PRD.OBSERVATION_RECORDED'
   OR NOT curve_sprd_shape(event.payload,curve_sprd_schema('observed-event'))
   OR event.payload->>'observation_id'<>NEW.id::text OR event.payload->>'observation_digest'<>NEW.digest
   OR event.payload->>'initiative_id'<>NEW.initiative_id::text
   OR event.actor IS DISTINCT FROM jsonb_build_object('actor_type','HUMAN','actor_id',NEW.created_by::text)
   OR event.effective_principal IS DISTINCT FROM event.actor
   OR NOT curve_sprd_created_here('curve_domain_event',NEW.workspace_id,event.id)
   OR NOT EXISTS(SELECT 1 FROM curve_outbox_event WHERE workspace_id=NEW.workspace_id AND event_id=event.id
      AND destination='CURVE_SCOPED_PRD_METADATA_V1' AND curve_sprd_created_here('curve_outbox_event',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_OBSERVATION_EVENT_REQUIRED' USING ERRCODE='23514';
  END IF;
  SELECT * INTO policy FROM curve_policy_decision WHERE workspace_id=NEW.workspace_id
   AND id=(event.payload->>'policy_decision_id')::uuid;
  IF NOT FOUND OR policy.action<>'CURVE.PRD.SUBMIT' OR policy.effect<>'ALLOW' OR policy.policy_key<>'CURVE_PRD_POLICY'
   OR policy.resource_type<>'INITIATIVE' OR policy.resource_id<>NEW.initiative_id
   OR policy.resource_version<>(NEW.payload->>'initiative_version')::bigint
   OR policy.subject IS DISTINCT FROM event.actor OR policy.effective_principal IS DISTINCT FROM event.actor
   OR NOT curve_sprd_created_here('curve_policy_decision',NEW.workspace_id,policy.id)
   OR NOT EXISTS(SELECT 1 FROM curve_audit_event WHERE workspace_id=NEW.workspace_id
      AND target_type='SCOPED_PRD_OBSERVATION' AND target_id=NEW.id AND outcome='SUCCEEDED'
      AND action='CURVE.SCOPED_PRD.OBSERVE' AND actor=event.actor
      AND policy_decision_ref=jsonb_build_object('resource_type','POLICY_DECISION','resource_id',policy.id::text,'resource_version',1)
      AND curve_sprd_created_here('curve_audit_event',workspace_id,id))
   OR NOT EXISTS(SELECT 1 FROM curve_idempotency_record WHERE workspace_id=NEW.workspace_id
      AND principal_scope='HUMAN:'||NEW.created_by::text
      AND command_scope='SCOPED_PRD_V1_OBSERVE:'||NEW.initiative_id::text
      AND key_digest=event.idempotency_key_digest AND state='COMPLETED' AND response_status=201
      AND response_resource_ref=jsonb_build_object('resource_type','SCOPED_PRD_OBSERVATION','resource_id',NEW.id::text,'resource_version',1)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_OBSERVATION_AUDIT_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_document_checkpoint' THEN
  IF EXISTS(SELECT 1 FROM curve_scope_proposal h JOIN curve_scope_proposal_item i
    ON i.workspace_id=h.workspace_id AND i.revision_id=h.current_revision_id
    WHERE h.workspace_id=NEW.workspace_id AND h.initiative_id=NEW.initiative_id AND i.purpose='PROPOSED_DELIVERY')
   AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
    AND initiative_id=NEW.initiative_id AND checkpoint_id=NEW.id
    AND curve_sprd_created_here('curve_scoped_prd_subject',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_CHECKPOINT_SIDECAR_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_prd_review_decision' THEN
  IF EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
    AND initiative_id=NEW.initiative_id AND checkpoint_id=NEW.checkpoint_id)
   AND NOT EXISTS(SELECT 1 FROM curve_scoped_prd_decision WHERE workspace_id=NEW.workspace_id
    AND initiative_id=NEW.initiative_id AND decision_id=NEW.id
    AND curve_sprd_created_here('curve_scoped_prd_decision',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_DECISION_SIDECAR_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_readiness' THEN
  IF NOT EXISTS(SELECT 1 FROM curve_scoped_prd_subject WHERE workspace_id=NEW.workspace_id
   AND initiative_id=NEW.initiative_id AND scoped_readiness_id=NEW.id
   AND curve_sprd_created_here('curve_scoped_prd_subject',workspace_id,id)) THEN
   RAISE EXCEPTION 'SCOPED_PRD_READINESS_SUBJECT_REQUIRED' USING ERRCODE='23514';
  END IF;
  RETURN NULL;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_subject' THEN completion_operation_id:=NEW.submission_operation_id;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_decision' THEN completion_operation_id:=NEW.review_operation_id;
 ELSIF TG_TABLE_NAME='curve_scoped_prd_accepted_command' THEN completion_operation_id:=NEW.operation_id;
 ELSE
  IF NEW.command_type NOT LIKE 'SCOPED_PRD_V1_%' THEN RETURN NULL; END IF;
  completion_operation_id:=NEW.id;
 END IF;
 SELECT * INTO op FROM curve_operation WHERE workspace_id=NEW.workspace_id AND id=completion_operation_id;
 SELECT * INTO cmd FROM curve_scoped_prd_accepted_command WHERE workspace_id=NEW.workspace_id AND operation_id=op.id;
 IF NOT FOUND OR op.command_type<>replace(cmd.action,'CURVE.PRD.','SCOPED_PRD_V1_') THEN
  RAISE EXCEPTION 'SCOPED_PRD_OPERATION_COMMAND_REQUIRED' USING ERRCODE='23514';
 END IF;
 IF TG_TABLE_NAME IN ('curve_scoped_prd_subject','curve_scoped_prd_decision') AND op.status<>'SUCCEEDED' THEN
  RAISE EXCEPTION 'SCOPED_PRD_ATOMIC_COMPLETION_REQUIRED' USING ERRCODE='23514';
 END IF;
 IF op.status<>'SUCCEEDED' THEN RETURN NULL; END IF;
 IF NOT EXISTS(SELECT 1 FROM curve_domain_event e JOIN curve_outbox_event o
   ON o.workspace_id=e.workspace_id AND o.event_id=e.id
   WHERE e.workspace_id=op.workspace_id AND e.aggregate_type='OPERATION' AND e.aggregate_id=op.id
    AND e.aggregate_version=op.aggregate_version AND e.event_type='curve.operation.state_changed'
    AND e.payload->>'status'='SUCCEEDED' AND o.destination='CURVE_SCOPED_PRD_CANDIDATE_V1'
    AND curve_sprd_created_here('curve_domain_event',e.workspace_id,e.id)
    AND curve_sprd_created_here('curve_outbox_event',o.workspace_id,o.id))
  OR NOT EXISTS(SELECT 1 FROM curve_audit_event a JOIN curve_policy_decision p
    ON p.workspace_id=a.workspace_id AND p.id::text=a.policy_decision_ref->>'resource_id'
   WHERE a.workspace_id=op.workspace_id AND a.action=cmd.action||'.COMPLETION' AND a.outcome='SUCCEEDED'
    AND a.target_type='INITIATIVE' AND a.target_id=cmd.initiative_id AND a.target_ref=op.result_ref
    AND a.actor=op.created_by AND a.causation_id=op.id::text
    AND p.action=cmd.action AND p.effect='ALLOW' AND p.policy_key='CURVE_PRD_POLICY'
    AND p.resource_type='INITIATIVE' AND p.resource_id=cmd.initiative_id AND p.resource_version=cmd.expected_version
    AND p.subject=op.created_by AND p.effective_principal=op.created_by
    AND curve_sprd_created_here('curve_audit_event',a.workspace_id,a.id)
    AND curve_sprd_created_here('curve_policy_decision',p.workspace_id,p.id)) THEN
  RAISE EXCEPTION 'SCOPED_PRD_ATOMIC_AUDIT_REQUIRED' USING ERRCODE='23514';
 END IF;
 SELECT * INTO init FROM curve_initiative WHERE workspace_id=op.workspace_id AND id=cmd.initiative_id;
 IF op.result_ref IS DISTINCT FROM jsonb_build_object('resource_type','INITIATIVE','resource_id',cmd.initiative_id::text,
    'resource_version',cmd.expected_version+1) THEN
  RAISE EXCEPTION 'SCOPED_PRD_OPERATION_RESULT_MISMATCH' USING ERRCODE='23514';
 END IF;
 IF cmd.action='CURVE.PRD.SUBMIT' THEN
  SELECT * INTO s FROM curve_scoped_prd_subject WHERE workspace_id=op.workspace_id
   AND initiative_id=cmd.initiative_id AND submission_operation_id=op.id;
  IF NOT FOUND OR NOT curve_sprd_created_here('curve_scoped_prd_subject',s.workspace_id,s.id)
   OR init.current_prd_checkpoint_id IS DISTINCT FROM s.checkpoint_id OR init.version<>cmd.expected_version+1
   OR init.state<>'PRD_REVIEW' OR init.controlling_prd_decision_id IS NOT NULL THEN
   RAISE EXCEPTION 'SCOPED_PRD_SUBMISSION_INCOMPLETE' USING ERRCODE='23514';
  END IF;
 ELSE
  SELECT * INTO d FROM curve_scoped_prd_decision WHERE workspace_id=op.workspace_id
   AND initiative_id=cmd.initiative_id AND review_operation_id=op.id;
  IF NOT FOUND OR NOT curve_sprd_created_here('curve_scoped_prd_decision',d.workspace_id,d.id)
   OR init.controlling_prd_decision_id IS DISTINCT FROM d.decision_id OR init.version<>cmd.expected_version+1
   OR init.state IS DISTINCT FROM (CASE WHEN cmd.action='CURVE.PRD.APPROVE' THEN 'PLANNING' ELSE 'ALIGNING' END) THEN
   RAISE EXCEPTION 'SCOPED_PRD_REVIEW_INCOMPLETE' USING ERRCODE='23514';
  END IF;
 END IF;
 RETURN NULL;
END $$;
DROP TRIGGER curve_reopen_no_truncate ON curve_scope_reopening;
DROP TRIGGER curve_reopen_idem_stamp ON curve_idempotency_record;
DROP TRIGGER curve_reopen_revision_stamp ON curve_scope_proposal_revision;
DROP TRIGGER curve_reopen_commit ON curve_scope_reopening;
DROP TRIGGER curve_reopen_stamp ON curve_scope_reopening;
DROP TRIGGER curve_reopen_record_guard ON curve_scope_reopening;
DROP TRIGGER curve_reopen_immutable ON curve_scope_reopening;
DROP FUNCTION curve_reopen_commit_guard();
DROP FUNCTION curve_reopen_verify_graph(curve_scope_reopening);
DROP FUNCTION curve_reopen_record_guard();
DROP FUNCTION curve_reopen_fence(curve_scope_reopening);
DROP FUNCTION curve_reopen_schema(text);
DROP FUNCTION curve_scope_reopening_verify_coverage();
DROP FUNCTION curve_scope_reopening_catalog();
DROP FUNCTION curve_reopen_coverage_immutable();
DROP TABLE curve_scope_reopening_coverage;
ALTER TABLE curve_initiative DROP CONSTRAINT curve_init_pending_reopen_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_init_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_product_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_proposal_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_revision_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_predecessor_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_checkpoint_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_decision_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_previous_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_policy_fk;
ALTER TABLE curve_scope_reopening DROP CONSTRAINT curve_reopen_event_fk;
"""
SEAL_GUARDS = r"""CREATE TRIGGER curve_reopen_coverage_immutable BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE
 ON curve_scope_reopening_coverage FOR EACH STATEMENT EXECUTE FUNCTION curve_reopen_coverage_immutable();"""


def verify_baseline(apps, schema_editor):
    """Reject drift before adding anything; never bless the observed deployment."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW search_path")
        previous_path = cursor.fetchone()[0]
        cursor.execute("SET LOCAL search_path = pg_catalog, public")
        cursor.execute("SELECT 'sha256:' || encode(sha256(convert_to((" + CATALOG_SQL + ")::text, 'UTF8')), 'hex')")
        actual = cursor.fetchone()[0]
        cursor.execute("SELECT set_config('search_path', %s, true)", [previous_path])
        if actual != BASELINE_CATALOG_DIGEST:
            raise RuntimeError("SCOPE_REOPENING_BASELINE_CATALOG_UNQUALIFIED")


def install_seal(apps, schema_editor):
    # The reviewed constant was computed only in a disposable database migrated
    # from verified predecessor bytes. Data is excluded from the structural hash.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "INSERT INTO curve_scope_reopening_coverage(edition,catalog_digest) VALUES (%s,%s)",
            ["CURVE_PRE_PLAN_C2B_V1", SUCCESSOR_CATALOG_DIGEST],
        )


def verify_successor(apps, schema_editor):
    # Include Django deferred indexes/FKs in the final catalog before qualification.
    for statement in schema_editor.deferred_sql:
        schema_editor.execute(statement)
    schema_editor.deferred_sql = []
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT curve_scope_reopening_verify_coverage()")


class Migration(migrations.Migration):
    dependencies = [
        ("curve", "0022_scoped_prd"),
    ]

    operations = [
        migrations.RunPython(verify_baseline, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ScopeReopening",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("workspace_id", models.UUIDField(db_index=True, editable=False)),
                ("product_id", models.UUIDField(editable=False)),
                ("initiative_id", models.UUIDField(db_index=True, editable=False)),
                ("proposal_id", models.UUIDField(editable=False)),
                ("scope_revision_id", models.UUIDField(editable=False, unique=True)),
                ("predecessor_revision_id", models.UUIDField(editable=False)),
                ("previous_initiative_version", models.PositiveBigIntegerField(editable=False)),
                ("previous_state", models.CharField(editable=False, max_length=40)),
                ("previous_checkpoint_id", models.UUIDField(editable=False, null=True)),
                ("previous_decision_id", models.UUIDField(editable=False, null=True)),
                ("previous_pending_reopening_id", models.UUIDField(editable=False, null=True)),
                ("created_by", models.UUIDField(editable=False)),
                ("reason_digest", models.CharField(editable=False, max_length=71)),
                ("request_digest", models.CharField(editable=False, max_length=71)),
                ("policy_decision_id", models.UUIDField(editable=False)),
                ("command_receipt_id", models.UUIDField(editable=False)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("digest", models.CharField(editable=False, max_length=71)),
                ("payload", models.JSONField(editable=False)),
            ],
            options={
                "db_table": "curve_scope_reopening",
            },
        ),
        migrations.RemoveConstraint(
            model_name="policydecision",
            name="curve_policy_identity_ck",
        ),
        migrations.RemoveConstraint(
            model_name="scopeproposalrevision",
            name="curve_scope_policy_ck",
        ),
        migrations.AddField(
            model_name="initiative",
            name="pending_scope_reopening_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="policydecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("policy_key", "CURVE_PROJECT_ASSOCIATION_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:0ea402f3db6a7fb0743a79a45644d79235a685781ad844d3c42230da2c548691",
                        ),
                        ("policy_version", 1),
                    ),
                    models.Q(
                        ("policy_key", "CURVE_SCOPE_PROPOSAL_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:778bdbd6fb82f51482d791d22ae6cf884a8906e91613b07cdafc6b429d24e266",
                        ),
                        ("policy_version", 1),
                    ),
                    models.Q(
                        ("policy_key", "CURVE_SCOPE_REOPENING_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:598e492b7dc23369eaf3029d7e208b4fd338d03d3e3388fcb10305e9c02b0094",
                        ),
                        ("policy_version", 1),
                    ),
                    models.Q(("policy_key", "CURVE_CORE_POLICY"), ("policy_version__in", [1, 2])),
                    models.Q(("policy_key", "CURVE_PRODUCT_POLICY"), ("policy_version", 1)),
                    models.Q(("policy_key", "CURVE_INITIATIVE_POLICY"), ("policy_version", 1)),
                    models.Q(
                        ("policy_key", "CURVE_PRD_POLICY"),
                        (
                            "policy_manifest_digest",
                            "sha256:ad38408f0e4450c615025debdf3361965f3a7361ad392aaf9aeb4219b910cb4c",
                        ),
                        ("policy_version", 1),
                    ),
                    _connector="OR",
                ),
                name="curve_policy_identity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopeproposalrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "policy_edition__in",
                        ["EXPLICIT_EXISTING_WORK_SCOPE_PROPOSAL_V1", "REOPENED_EXISTING_WORK_SCOPE_PROPOSAL_V1"],
                    )
                ),
                name="curve_scope_policy_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopereopening",
            constraint=models.UniqueConstraint(
                fields=("workspace_id", "initiative_id", "id"), name="curve_reopen_scope_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopereopening",
            constraint=models.CheckConstraint(
                condition=models.Q(("digest__regex", "^sha256:[0-9a-f]{64}$")), name="curve_reopen_digest_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopereopening",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason_digest__regex", "^sha256:[0-9a-f]{64}$")), name="curve_reopen_reason_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopereopening",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_digest__regex", "^sha256:[0-9a-f]{64}$")), name="curve_reopen_request_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopereopening",
            constraint=models.CheckConstraint(
                condition=models.Q(("previous_initiative_version__gte", 1)), name="curve_reopen_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopereopening",
            constraint=models.CheckConstraint(
                condition=models.Q(("previous_state__in", ["ALIGNING", "PRD_REVIEW", "PLANNING"])),
                name="curve_reopen_state_ck",
            ),
        ),
        migrations.RunSQL(FORWARD_GUARDS, REVERSE_GUARDS),
        migrations.RunPython(install_seal, migrations.RunPython.noop),
        migrations.RunSQL(
            SEAL_GUARDS, "DROP TRIGGER curve_reopen_coverage_immutable ON curve_scope_reopening_coverage;"
        ),
        migrations.RunPython(verify_successor, migrations.RunPython.noop),
    ]
