/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * Generated by generate-existing-work-validators.mjs; do not edit.
 */
import type {
  CurveProjectAssociationCreate,
  CurveProjectAssociationEnd,
  CurveProjectAssociation,
  CurveScopeProposalReplace,
  CurveScopeProposalRevision,
  CurveScopedPrdObserveV1,
  CurveScopedPrdObservationV1,
  CurveScopedPrdSubjectV1,
  CurveScopedPrdSubmitV1,
  CurveScopedPrdApproveV1,
  CurveScopedPrdReturnV1,
  CurveScopeReopeningPreconditionsV1,
} from "@plane/types";
export declare const validateCurveProjectAssociationCreate: {
  (input: unknown): input is CurveProjectAssociationCreate;
  errors?: unknown;
};
export declare const validateCurveProjectAssociationEnd: {
  (input: unknown): input is CurveProjectAssociationEnd;
  errors?: unknown;
};
export declare const validateCurveProjectAssociation: {
  (input: unknown): input is CurveProjectAssociation;
  errors?: unknown;
};
export declare const validateCurveScopeProposalReplace: {
  (input: unknown): input is CurveScopeProposalReplace;
  errors?: unknown;
};
export declare const validateCurveScopeProposalRevision: {
  (input: unknown): input is CurveScopeProposalRevision;
  errors?: unknown;
};
export declare const validateCurveScopedPrdObserveV1: {
  (input: unknown): input is CurveScopedPrdObserveV1;
  errors?: unknown;
};
export declare const validateCurveScopedPrdObservationV1: {
  (input: unknown): input is CurveScopedPrdObservationV1;
  errors?: unknown;
};
export declare const validateCurveScopedPrdSubjectV1: {
  (input: unknown): input is CurveScopedPrdSubjectV1;
  errors?: unknown;
};
export declare const validateCurveScopedPrdSubmitV1: {
  (input: unknown): input is CurveScopedPrdSubmitV1;
  errors?: unknown;
};
export declare const validateCurveScopedPrdApproveV1: {
  (input: unknown): input is CurveScopedPrdApproveV1;
  errors?: unknown;
};
export declare const validateCurveScopedPrdReturnV1: {
  (input: unknown): input is CurveScopedPrdReturnV1;
  errors?: unknown;
};
export declare const validateCurveScopeReopeningPreconditionsV1: {
  (input: unknown): input is CurveScopeReopeningPreconditionsV1;
  errors?: unknown;
};
